site_name: BB Web DS Tools Wiki
docs_dir: wiki
site_dir: docs/wiki
repo_url: https://github.com/davidpham87/bb-web-ds-tools
repo_name: GitHub
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search
