(ns bb-web-ds-tools.views.landing.tour
  "View component for tour.

  Key functionality: tour-features, product-tour"
  (:require [reagent.core :as r]
            [bb-web-ds-tools.components.landing :as landing]
            [bb-web-ds-tools.components.landing.animations :as animations]
            [bb-web-ds-tools.theme :as t]))

(def tour-features
  [{:id :repl
    :title "Interactive REPL"
    :desc "Evaluate ClojureScript code instantly. Inspect state, test functions, and prototype with a persistent environment."
    :why "Because you clearly can't decide which language is superior, so we gave you all of them to fail in simultaneously. Whether you're a Pythonista, a recovering R user, or a Clojure purist who thinks syntax is for the weak, we have a padded cell waiting for you."
    :icon [:svg {:xmlns "http://www.w3.org/2000/svg" :width "24" :height "24" :viewBox "0 0 24 24" :fill "none" :stroke "currentColor" :stroke-width "2" :stroke-linecap "round" :stroke-linejoin "round"} [:polyline {:points "4 17 10 11 4 5"}] [:line {:x1 "12" :y1 "19" :x2 "20" :y2 "19"}]]
    :color "text-green-400"
    :draw-fn animations/draw-code}
   {:id :vega-lite
    :title "Vega Lite Visualization"
    :desc "Create complex, interactive visualizations using a declarative JSON syntax. Instant feedback loop."
    :why "Because looking at raw numbers makes your eyes bleed, and you need a pretty chart to distract your manager from the fact that revenue is down. Or maybe you just like pretty colors. We don't judge. Much."
    :icon [:svg {:xmlns "http://www.w3.org/2000/svg" :width "24" :height "24" :viewBox "0 0 24 24" :fill "none" :stroke "currentColor" :stroke-width "2" :stroke-linecap "round" :stroke-linejoin "round"} [:bar-chart {:width "24" :height "24"}] [:line {:x1 "18" :y1 "20" :x2 "18" :y2 "10"}] [:line {:x1 "12" :y1 "20" :x2 "12" :y2 "4"}] [:line {:x1 "6" :y1 "20" :x2 "6" :y2 "14"}]]
    :color "text-blue-400"
    :draw-fn animations/draw-vega-lite}
   {:id :honeysql
    :title "HoneySQL Editor"
    :desc "Compose SQL queries as Clojure data structures. formatting, and raw SQL generation included."
    :why "Because writing raw SQL strings is so 1999, and we prefer our SQL injection vulnerabilities to be at least slightly more difficult to achieve. Also, because you secretly love Lisp parentheses more than you love readable query languages."
    :icon [:svg {:xmlns "http://www.w3.org/2000/svg" :width "24" :height "24" :viewBox "0 0 24 24" :fill "none" :stroke "currentColor" :stroke-width "2" :stroke-linecap "round" :stroke-linejoin "round"} [:ellipse {:cx "12" :cy "5" :rx "9" :ry "3"}] [:path {:d "M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"}] [:path {:d "M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"}]]
    :color "text-yellow-400"
    :draw-fn animations/draw-honeysql}
   {:id :malli
    :title "Malli Schema"
    :desc "Validate your data with powerful schemas. Generate inputs, test edges, and ensure data integrity."
    :why "Because your data is messy, unorganized, and frankly, a little embarrassing. It's time to bring some law and order to that wild west of a map you call a \"data structure.\" Think of Malli as the strict librarian who shushes your data into compliance."
    :icon [:svg {:xmlns "http://www.w3.org/2000/svg" :width "24" :height "24" :viewBox "0 0 24 24" :fill "none" :stroke "currentColor" :stroke-width "2" :stroke-linecap "round" :stroke-linejoin "round"} [:path {:d "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"}] [:path {:d "M9 12l2 2 4-4"}]]
    :color "text-purple-400"
    :draw-fn animations/draw-malli}
   {:id :datasets
    :title "Dataset Manager"
    :desc "Import, view, and transform CSV/JSON datasets. Your local data hub for quick analysis."
    :why "Because manual data entry is a form of torture banned by the Geneva Convention. You're here because you have data in a format that looks like it was generated by a drunk typewriter, and you need it to look like a respectable table before your boss asks why the Q3 projections are written in Sanskrit."
    :icon [:svg {:xmlns "http://www.w3.org/2000/svg" :width "24" :height "24" :viewBox "0 0 24 24" :fill "none" :stroke "currentColor" :stroke-width "2" :stroke-linecap "round" :stroke-linejoin "round"} [:rect {:x "3" :y "3" :width "18" :height "18" :rx "2" :ry "2"}] [:line {:x1 "3" :y1 "9" :x2 "21" :y2 "9"}] [:line {:x1 "9" :y1 "21" :x2 "9" :y2 "9"}]]
    :color "text-orange-400"
    :draw-fn animations/draw-datasets}])

(defn product-tour
  "A product tour component showcasing different views."
  []
  (let [active-idx (r/atom 0)
        touch-start (r/atom nil)
        touch-end (r/atom nil)
        min-swipe-distance 50

        handle-touch-start (fn [e]
                             (reset! touch-end nil)
                             (reset! touch-start (-> e .-targetTouches (aget 0) .-clientX)))

        handle-touch-move (fn [e]
                            (reset! touch-end (-> e .-targetTouches (aget 0) .-clientX)))

        handle-touch-end (fn []
                           (when (and @touch-start @touch-end)
                             (let [distance (- @touch-start @touch-end)
                                   is-left-swipe (> distance min-swipe-distance)
                                   is-right-swipe (< distance (- min-swipe-distance))
                                   count (count tour-features)]
                               (cond
                                 is-left-swipe (swap! active-idx #(mod (inc %) count))
                                 is-right-swipe (swap! active-idx #(mod (dec %) count))))))]
    (fn []
      [:div {:class "w-full max-w-7xl mx-auto py-20 px-4"}
       [:h2 {:class (str "text-4xl font-bold mb-12 text-center " t/text-primary) } "Explore the Views"]

       [:div {:class "grid grid-cols-1 lg:grid-cols-2 gap-12 items-start"}
        ;; Left Column: Triggers
        [:div {:class "space-y-4 hidden lg:block"}
         (into [:<>]
               (map-indexed
                (fn [idx {:keys [id title desc icon color]}]
                  (let [active? (= idx @active-idx)]
                    ^{:key id}
                    [:button {:on-click #(reset! active-idx idx)
                              :class (str "w-full text-left p-6 rounded-xl transition-all duration-300 border "
                                          (if active?
                                            (str t/bg-card " border-l-4 " t/border-accent " shadow-lg scale-[1.02]")
                                            (str "bg-transparent " t/border-subtle " hover:bg-opacity-50 hover:" t/bg-sidebar)))}
                     [:div {:class "flex items-start gap-4"}
                      [:div {:class (str "p-2 rounded-lg bg-opacity-10 " (if active? color "text-gray-400"))}
                       icon]
                      [:div
                       [:h3 {:class (str "text-xl font-bold mb-2 " (if active? t/text-primary t/text-muted))} title]
                       [:p {:class (str "text-sm leading-relaxed " t/text-secondary)} desc]]]]))
                tour-features))]

        ;; Right Column: Content Preview (Swipeable)
        [:div {:class (str "relative rounded-2xl border " t/border-subtle " bg-transparent shadow-2xl overflow-hidden min-h-[500px] flex items-center justify-center p-8 pt-2 transition-all duration-500 touch-pan-y")
               :on-touch-start handle-touch-start
               :on-touch-move handle-touch-move
               :on-touch-end handle-touch-end}
         (let [{:keys [title color id draw-fn why]} (nth tour-features @active-idx)]
           [:div {:key id :class "text-center animate-fade-in-up flex flex-col items-center justify-center h-full w-full select-none"}
            [:div {:class (str "mb-6 " color)}
             [landing/animated-icon {:draw-fn draw-fn :class "w-48 h-48 bg-transparent"}]]
            [:h3 {:class (str "text-3xl font-bold mb-4 " t/text-primary)} title]
            [:p {:class (str "text-lg " t/text-secondary " max-w-lg leading-relaxed font-light italic")} why]

            ;; Mobile indicators
            [:div {:class "flex gap-2 justify-center mt-8"}
             (into [:<>]
                   (map-indexed
                    (fn [idx _]
                      ^{:key idx}
                      [:div {:class (str "w-2 h-2 rounded-full transition-all "
                                         (if (= idx @active-idx)
                                           (str "bg-" color " w-4")
                                           (str t/bg-button)))}])
                    tour-features))]])]]])))
