importScripts("shared.js");
(function(){
'use strict';var cljs$cst$4561$print=new $APP.cljs.core.Keyword(null,"print","print",1299562414),cljs$cst$4562$printErr=new $APP.cljs.core.Keyword(null,"printErr","printErr",-1323332006);var module$shadow_js_shim_module$$sqlite_org$sqlite_wasm={};$APP.shadow.js.shim.module$$sqlite_org$sqlite_wasm=$APP.shadow.js.nativeProvides["@sqlite.org/sqlite-wasm"]=shadow$bridge("@sqlite.org/sqlite-wasm");module$shadow_js_shim_module$$sqlite_org$sqlite_wasm.default=$APP.shadow.js.shim.module$$sqlite_org$sqlite_wasm;$APP.bb_web_ds_tools.workers.persistence={};$APP.bb_web_ds_tools.workers.persistence.sqlite_db=$APP.cljs.core.atom.cljs$core$IFn$_invoke$arity$1(null);$APP.bb_web_ds_tools.workers.persistence.log=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=0<b.length?new $APP.cljs.core.IndexedSeq(b.slice(0),0,null):null;return $APP.bb_web_ds_tools.workers.persistence.log.cljs$core$IFn$_invoke$arity$variadic(b)};
$APP.bb_web_ds_tools.workers.persistence.log.cljs$core$IFn$_invoke$arity$variadic=function(a){return $APP.cljs.core.apply.cljs$core$IFn$_invoke$arity$3(console.log,"[Worker]",a)};$APP.bb_web_ds_tools.workers.persistence.log.cljs$lang$maxFixedArity=0;$APP.bb_web_ds_tools.workers.persistence.log.cljs$lang$applyTo=function(a){return this.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.seq(a))};
$APP.bb_web_ds_tools.workers.persistence.error=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=0<b.length?new $APP.cljs.core.IndexedSeq(b.slice(0),0,null):null;return $APP.bb_web_ds_tools.workers.persistence.error.cljs$core$IFn$_invoke$arity$variadic(b)};$APP.bb_web_ds_tools.workers.persistence.error.cljs$core$IFn$_invoke$arity$variadic=function(a){return $APP.cljs.core.apply.cljs$core$IFn$_invoke$arity$3(console.error,"[Worker]",a)};
$APP.bb_web_ds_tools.workers.persistence.error.cljs$lang$maxFixedArity=0;$APP.bb_web_ds_tools.workers.persistence.error.cljs$lang$applyTo=function(a){return this.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.seq(a))};
$APP.bb_web_ds_tools.workers.persistence.start=function(a){$APP.bb_web_ds_tools.workers.persistence.log.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Running SQLite3 version",a.version.libVersion],0));var b=a.oo1.opfs!=null;a=b?new a.oo1.OpfsDb("/mydb.sqlite3"):new a.oo1.DB("/mydb.sqlite3","ct");$APP.cljs.core.reset_BANG_($APP.bb_web_ds_tools.workers.persistence.sqlite_db,a);return $APP.bb_web_ds_tools.workers.persistence.log.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([b?
["OPFS is available, created persisted database at ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(a.filename)].join(""):["OPFS is not available, created transient database ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(a.filename)].join("")],0))};
$APP.bb_web_ds_tools.workers.persistence.init=function(){var a=$APP.cljs.core.async.chan.cljs$core$IFn$_invoke$arity$1(1);$APP.cljs.core.async.impl.dispatch.run(function(){var b=function(){var d=function(e){var f=e[1];if(f===7)return f=e[7],f=$APP.cljs.core.ex_data(f),f=$APP.cljs$cst$1524$error.cljs$core$IFn$_invoke$arity$1(f),f=$APP.cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(f,$APP.cljs$cst$1525$promise_error),e[2]=f,e[1]=9,$APP.cljs$cst$283$recur;if(f===1)return e[2]=null,e[1]=2,$APP.cljs$cst$283$recur;
if(f===4)return f=e[2],f=$APP.bb_web_ds_tools.workers.persistence.error.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Initialization error:",f.name,f.message],0)),e[2]=f,e[1]=3,$APP.cljs$cst$283$recur;if(f===6){var g=e[2];f=g instanceof $APP.cljs.core.ExceptionInfo;e[7]=g;e[8]=f;$APP.cljs.core.truth_(f)?e[1]=7:e[1]=8;return $APP.cljs$cst$283$recur}if(f===3)return $APP.cljs.core.async.impl.ioc_helpers.return_chan(e,e[2]);if(f===12)return g=e[2],f=$APP.bb_web_ds_tools.workers.persistence.log.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Done initializing."],
0)),g=$APP.bb_web_ds_tools.workers.persistence.start(g),e[4]=$APP.cljs.core.rest(e[4]),e[9]=f,e[2]=g,e[1]=3,$APP.cljs$cst$283$recur;if(f===2)return e[4]=$APP.cljs.core.cons(5,e[4]),f=$APP.bb_web_ds_tools.workers.persistence.log.cljs$core$IFn$_invoke$arity$variadic($APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Loading and initializing SQLite3 module..."],0)),g=$APP.cljs.core.PersistentHashMap.fromArrays([cljs$cst$4561$print,cljs$cst$4562$printErr],[$APP.bb_web_ds_tools.workers.persistence.log,
$APP.bb_web_ds_tools.workers.persistence.error]),g=$APP.cljs.core.clj__GT_js(g),g=$APP.shadow.js.shim.module$$sqlite_org$sqlite_wasm.default(g),g=$APP.cljs.core.async.interop.p__GT_c(g),e[10]=f,$APP.cljs.core.async.impl.ioc_helpers.take_BANG_(e,6,g);if(f===11)return f=e[7],e[2]=f,e[1]=12,$APP.cljs$cst$283$recur;if(f===9)return f=e[2],$APP.cljs.core.truth_(f)?e[1]=10:e[1]=11,$APP.cljs$cst$283$recur;if(f===5)return e[4]=$APP.cljs.core.rest(e[4]),e[5]=e[2],e[1]=4,e[5]=null,$APP.cljs$cst$283$recur;if(f===
10)throw f=e[7],f;return f===8?(f=e[8],e[2]=f,e[1]=9,$APP.cljs$cst$283$recur):null};return function(){var e=null,f=function(){var h=[null,null,null,null,null,null,null,null,null,null,null];h[0]=e;h[1]=1;return h},g=function(h){for(;;){a:{try{for(;;){var k=d(h);if(!$APP.cljs.core.keyword_identical_QMARK_(k,$APP.cljs$cst$283$recur)){var l=k;break a}}}catch(m){l=m;h[2]=l;if($APP.cljs.core.seq(h[4]))h[1]=$APP.cljs.core.first(h[4]);else throw l;l=$APP.cljs$cst$283$recur;break a}l=void 0}if(!$APP.cljs.core.keyword_identical_QMARK_(l,
$APP.cljs$cst$283$recur))return l}};e=function(h){switch(arguments.length){case 0:return f.call(this);case 1:return g.call(this,h)}throw Error("Invalid arity: "+arguments.length);};e.cljs$core$IFn$_invoke$arity$0=f;e.cljs$core$IFn$_invoke$arity$1=g;return e}()}(),c=function(){var d=b();d[6]=a;return d}();return $APP.cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped(c)});return a};$APP.goog.exportSymbol("bb_web_ds_tools.workers.persistence.init",$APP.bb_web_ds_tools.workers.persistence.init);$APP.bb_web_ds_tools.workers.persistence.init();
}).call(this);