importScripts("shared.js");
(function(){
'use strict';var cljs$cst$4527$__arr=new $APP.cljs.core.Symbol(null,"__arr","__arr",2056204649,null),cljs$cst$4529$key__GT_prop=new $APP.cljs.core.Keyword(null,"key-\x3eprop","key-\x3eprop",-1028452531),cljs$cst$4530$recursive=new $APP.cljs.core.Keyword(null,"recursive","recursive",718885872),cljs$cst$4528$prop__GT_key=new $APP.cljs.core.Keyword(null,"prop-\x3ekey","prop-\x3ekey",-1297715246),cljs$cst$4532$sync_main=new $APP.cljs.core.Keyword(null,"sync-main","sync-main",-791286349),cljs$cst$4524$key__GT_prop=
new $APP.cljs.core.Symbol(null,"key-\x3eprop","key-\x3eprop",612078996,null),cljs$cst$4526$__cnt=new $APP.cljs.core.Symbol(null,"__cnt","__cnt",1833584904,null),cljs$cst$4533$patch_datasets=new $APP.cljs.core.Keyword(null,"patch-datasets","patch-datasets",1386268626),cljs$cst$4523$prop__GT_key=new $APP.cljs.core.Symbol(null,"prop-\x3ekey","prop-\x3ekey",342816281,null),cljs$cst$4531$datasets=new $APP.cljs.core.Symbol(null,"datasets","datasets",-758071350,null),cljs$cst$4525$transform=new $APP.cljs.core.Symbol(null,
"transform","transform",-1273134005,null),cljs$cst$4534$warning=new $APP.cljs.core.Keyword(null,"warning","warning",-1685650671);var cljs_bean={from:{}};cljs_bean.from.cljs={};cljs_bean.from.cljs.core={};cljs_bean.from.cljs.core._indexOf=function(a){switch(arguments.length){case 2:return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$2(arguments[0],arguments[1]);case 3:return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""));}};
cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$2=function(a,b){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(a,b,0)};cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3=function(a,b,c){var d=$APP.cljs.core.count(a);if(c>=d)return-1;!(c>0)&&c<0&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if($APP.cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2($APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$2(a,c),b))return c;c+=1}else return-1};
cljs_bean.from.cljs.core._indexOf.cljs$lang$maxFixedArity=3;cljs_bean.from.cljs.core._lastIndexOf=function(a){switch(arguments.length){case 2:return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$2(arguments[0],arguments[1]);case 3:return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""));}};
cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$2=function(a,b){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(a,b,$APP.cljs.core.count(a))};cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3=function(a,b,c){var d=$APP.cljs.core.count(a);if(d===0)return-1;c>0?(--d,c=d<c?d:c):c=c<0?d+c:c;for(;;)if(c>=0){if($APP.cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2($APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$2(a,c),b))return c;--c}else return-1};
cljs_bean.from.cljs.core._lastIndexOf.cljs$lang$maxFixedArity=3;
cljs_bean.from.cljs.core.compare_indexed=function(a){switch(arguments.length){case 2:return cljs_bean.from.cljs.core.compare_indexed.cljs$core$IFn$_invoke$arity$2(arguments[0],arguments[1]);case 4:return cljs_bean.from.cljs.core.compare_indexed.cljs$core$IFn$_invoke$arity$4(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""));}};
cljs_bean.from.cljs.core.compare_indexed.cljs$core$IFn$_invoke$arity$2=function(a,b){var c=$APP.cljs.core.count(a),d=$APP.cljs.core.count(b);return c<d?-1:c>d?1:c===0?0:cljs_bean.from.cljs.core.compare_indexed.cljs$core$IFn$_invoke$arity$4(a,b,c,0)};
cljs_bean.from.cljs.core.compare_indexed.cljs$core$IFn$_invoke$arity$4=function(a,b,c,d){for(;;){var e=$APP.cljs.core.compare($APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$2(a,d),$APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$2(b,d));if(e===0&&d+1<c)d+=1;else return e}};cljs_bean.from.cljs.core.compare_indexed.cljs$lang$maxFixedArity=4;
cljs_bean.from.cljs.core.equiv_sequential=function(a,b){var c=$APP.cljs.core,d=c.boolean$;if($APP.cljs.core.sequential_QMARK_(b))if($APP.cljs.core.counted_QMARK_(a)&&$APP.cljs.core.counted_QMARK_(b)&&$APP.cljs.core.count(a)!==$APP.cljs.core.count(b))a=!1;else a:{a=$APP.cljs.core.seq(a);for(b=$APP.cljs.core.seq(b);;){if(a==null){a=b==null;break a}if(b!=null&&$APP.cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2($APP.cljs.core.first(a),$APP.cljs.core.first(b)))a=$APP.cljs.core.next(a),b=$APP.cljs.core.next(b);
else{a=!1;break a}}a=void 0}else a=null;return d.call(c,a)};
cljs_bean.from.cljs.core.ci_reduce=function(a){switch(arguments.length){case 2:return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$2(arguments[0],arguments[1]);case 3:return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$3(arguments[0],arguments[1],arguments[2]);case 4:return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$4(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""));
}};cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$2=function(a,b){var c=a.cljs$core$ICounted$_count$arity$1(null);if(c===0)return b.cljs$core$IFn$_invoke$arity$0?b.cljs$core$IFn$_invoke$arity$0():b.call(null);for(var d=a.cljs$core$IIndexed$_nth$arity$2(null,0),e=1;;)if(e<c){var f=a.cljs$core$IIndexed$_nth$arity$2(null,e);d=b.cljs$core$IFn$_invoke$arity$2?b.cljs$core$IFn$_invoke$arity$2(d,f):b.call(null,d,f);if($APP.cljs.core.reduced_QMARK_(d))return $APP.cljs.core.deref(d);e+=1}else return d};
cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$3=function(a,b,c){var d=a.cljs$core$ICounted$_count$arity$1(null),e=c;for(c=0;;)if(c<d){var f=a.cljs$core$IIndexed$_nth$arity$2(null,c);e=b.cljs$core$IFn$_invoke$arity$2?b.cljs$core$IFn$_invoke$arity$2(e,f):b.call(null,e,f);if($APP.cljs.core.reduced_QMARK_(e))return $APP.cljs.core.deref(e);c+=1}else return e};
cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$4=function(a,b,c,d){for(var e=a.cljs$core$ICounted$_count$arity$1(null);;)if(d<e){var f=a.cljs$core$IIndexed$_nth$arity$2(null,d);c=b.cljs$core$IFn$_invoke$arity$2?b.cljs$core$IFn$_invoke$arity$2(c,f):b.call(null,c,f);if($APP.cljs.core.reduced_QMARK_(c))return $APP.cljs.core.deref(c);d+=1}else return c};cljs_bean.from.cljs.core.ci_reduce.cljs$lang$maxFixedArity=4;
cljs_bean.from.cljs.core.TransientArrayMap_conj_BANG_=function(a,b,c){if($APP.cljs.core.truth_(c)){if($APP.cljs.core.map_entry_QMARK_(b))return a.cljs$core$ITransientAssociative$_assoc_BANG_$arity$3(null,$APP.cljs.core.key(b),$APP.cljs.core.val(b));if($APP.cljs.core.vector_QMARK_(b))return a.cljs$core$ITransientAssociative$_assoc_BANG_$arity$3(null,b.cljs$core$IFn$_invoke$arity$1?b.cljs$core$IFn$_invoke$arity$1(0):b.call(null,0),b.cljs$core$IFn$_invoke$arity$1?b.cljs$core$IFn$_invoke$arity$1(1):b.call(null,
1));for(b=$APP.cljs.core.seq(b);;)if(c=$APP.cljs.core.first(b),$APP.cljs.core.truth_(c))b=$APP.cljs.core.next(b),a=$APP.cljs.core._assoc_BANG_(a,$APP.cljs.core.key(c),$APP.cljs.core.val(c));else return a}else throw Error("conj! after persistent!");};
cljs_bean.from.cljs.core.PersistentArrayMap_conj=function(a,b){if($APP.cljs.core.vector_QMARK_(b))return a.cljs$core$IAssociative$_assoc$arity$3(null,$APP.cljs.core._nth(b,0),$APP.cljs.core._nth(b,1));for(b=$APP.cljs.core.seq(b);;){if(b==null)return a;var c=$APP.cljs.core.first(b);if($APP.cljs.core.vector_QMARK_(c))a=$APP.cljs.core._assoc(a,$APP.cljs.core._nth(c,0),$APP.cljs.core._nth(c,1)),b=$APP.cljs.core.next(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
cljs_bean.from.cljs.core.TransientVector_assoc_BANG_=function(a,b,c,d){if(typeof b==="number")return a.cljs$core$ITransientVector$_assoc_n_BANG_$arity$3(null,b,c);throw Error([$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(d),"'s key for assoc! must be a number."].join(""));};
cljs_bean.from.cljs.core.PersistentVector_equiv=function(a,b,c,d){if(b instanceof c)if(d===$APP.cljs.core.count(b))for(a=a.cljs$core$IIterable$_iterator$arity$1(null),b=$APP.cljs.core._iterator(b);;){if(a.hasNext())if(c=a.next(),d=b.next(),$APP.cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(c,d))continue;else return!1;else return!0;break}else return!1;else return cljs_bean.from.cljs.core.equiv_sequential(a,b)};
cljs_bean.from.cljs.core.PersistentVector_lookup=function(a,b,c){return typeof b==="number"?a.cljs$core$IIndexed$_nth$arity$3(null,b,c):c};cljs_bean.from.cljs.core.PersistentVector_assoc=function(a,b,c){if(typeof b==="number")return a.cljs$core$IVector$_assoc_n$arity$3(null,b,c);throw Error("Vector's key for assoc must be a number.");};cljs_bean.from.cljs.core.PersistentVector_contains_key_QMARK_=function(a,b,c){return $APP.cljs.core.integer_QMARK_(b)?0<=b&&b<c:!1};cljs_bean.core={};cljs_bean.core.goog$module$goog$object=$APP.goog.object;cljs_bean.core.lookup_sentinel={};cljs_bean.core.primitive_QMARK_=function(a){return typeof a==="number"||typeof a==="string"||$APP.cljs.core.boolean_QMARK_(a)||a==null};
cljs_bean.core.__GT_val=function(a,b,c,d){var e=d!=null?d.cljs$core$IFn$_invoke$arity$1?d.cljs$core$IFn$_invoke$arity$1(a):d.call(null,a):null;return e==null?cljs_bean.core.primitive_QMARK_(a)?a:$APP.cljs.core.object_QMARK_(a)?new cljs_bean.core.Bean(null,a,b,c,d,!0,null,null,null):$APP.cljs.core.array_QMARK_(a)?new cljs_bean.core.ArrayVector(null,b,c,d,a,null):a:e};
cljs_bean.core.unwrap=function(a){return cljs_bean.core.primitive_QMARK_(a)?a:a instanceof cljs_bean.core.Bean?a.obj:a instanceof cljs_bean.core.ArrayVector?a.arr:a};cljs_bean.core.empty_map=$APP.cljs.core.PersistentArrayMap.EMPTY;
cljs_bean.core.snapshot=function(a,b,c,d,e){var f=$APP.cljs.core.volatile_BANG_($APP.cljs.core.transient$(cljs_bean.core.empty_map));cljs_bean.core.goog$module$goog$object.forEach(a,function(g,h,k){k=f.cljs$core$IVolatile$_vreset_BANG_$arity$2;var l=$APP.cljs.core.assoc_BANG_,m=l.cljs$core$IFn$_invoke$arity$3,n=f.cljs$core$IDeref$_deref$arity$1(null);h=b.cljs$core$IFn$_invoke$arity$1?b.cljs$core$IFn$_invoke$arity$1(h):b.call(null,h);g=$APP.cljs.core.truth_(e)?cljs_bean.core.__GT_val(g,b,c,d):g;return k.call(f,
null,m.call(l,n,h,g))});return $APP.cljs.core.persistent_BANG_($APP.cljs.core.deref(f))};cljs_bean.core.snapshot_arr=function(a){var b=$APP.cljs.core,c=b.vec;a:{for(var d=a.length,e=$APP.cljs.core.aclone(a),f=0;;)if(f<d){var g=f;var h=a[f];h=cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1?cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1(h):cljs_bean.core.__GT_clj.call(null,h);e[g]=h;f+=1}else{a=e;break a}a=void 0}return c.call(b,a)};
cljs_bean.core.indexed_entry=function(a,b,c,d,e,f,g){var h=f[g];f=$APP.cljs.core.MapEntry;g=b.cljs$core$IFn$_invoke$arity$1?b.cljs$core$IFn$_invoke$arity$1(h):b.call(null,h);a=a[h];b=e?cljs_bean.core.__GT_val(a,b,c,d):a;return new f(g,b,null)};cljs_bean.core.compatible_key_QMARK_=function(a,b){return a instanceof $APP.cljs.core.Keyword&&b===$APP.cljs.core.keyword||typeof a==="string"&&b===$APP.cljs.core.identity};
cljs_bean.core.compatible_value_QMARK_=function(a,b){var c;if(!(c=cljs_bean.core.primitive_QMARK_(a))&&(c=!($APP.cljs.core.map_QMARK_(a)&&!(a instanceof cljs_bean.core.Bean)||$APP.cljs.core.vector_QMARK_(a)&&!(a instanceof cljs_bean.core.ArrayVector)))){c=$APP.cljs.core;var d=c.not;a=$APP.cljs.core.truth_(b)?$APP.cljs.core.object_QMARK_(a)||$APP.cljs.core.array_QMARK_(a):b;c=d.call(c,a)}return c};
cljs_bean.core.snapshot_QMARK_=function(a,b,c,d){return!(cljs_bean.core.compatible_key_QMARK_(a,c)&&cljs_bean.core.compatible_value_QMARK_(b,d))};cljs_bean.core.TransientBean=function(a,b,c,d,e,f,g){this.editable_QMARK_=a;this.obj=b;this.prop__GT_key=c;this.key__GT_prop=d;this.transform=e;this.recursive_QMARK_=f;this.__cnt=g;this.cljs$lang$protocol_mask$partition0$=259;this.cljs$lang$protocol_mask$partition1$=56};
cljs_bean.core.TransientBean.prototype.cljs$core$ILookup$_lookup$arity$2=function(a,b){if(this.editable_QMARK_)return a=this.obj[this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b)],this.recursive_QMARK_?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a;throw Error("lookup after persistent!");};
cljs_bean.core.TransientBean.prototype.cljs$core$ILookup$_lookup$arity$3=function(a,b,c){if(this.editable_QMARK_)return a=cljs_bean.core.goog$module$goog$object.get(this.obj,this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b),c),this.recursive_QMARK_&&a!==c?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a;throw Error("lookup after persistent!");};
cljs_bean.core.TransientBean.prototype.cljs$core$ICounted$_count$arity$1=function(a){return this.__cnt==null?this.__cnt=$APP.cljs.core.count($APP.cljs.core.js_keys(this.obj)):this.__cnt};cljs_bean.core.TransientBean.prototype.cljs$core$ITransientCollection$_conj_BANG_$arity$2=function(a,b){return cljs_bean.from.cljs.core.TransientArrayMap_conj_BANG_(this,b,this.editable_QMARK_)};
cljs_bean.core.TransientBean.prototype.cljs$core$ITransientCollection$_persistent_BANG_$arity$1=function(a){if(this.editable_QMARK_)return this.editable_QMARK_=!1,new cljs_bean.core.Bean(null,this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,null,this.__cnt,null);throw Error("persistent! called twice");};
cljs_bean.core.TransientBean.prototype.cljs$core$ITransientAssociative$_assoc_BANG_$arity$3=function(a,b,c){if(this.editable_QMARK_){if(cljs_bean.core.snapshot_QMARK_(b,c,this.prop__GT_key,this.recursive_QMARK_))return $APP.cljs.core._assoc_BANG_($APP.cljs.core.transient$(cljs_bean.core.snapshot(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_)),b,c);a=this.obj;b=this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,
b);c=this.recursive_QMARK_?cljs_bean.core.unwrap(c):c;a[b]=c;this.__cnt=null;return this}throw Error("assoc! after persistent!");};cljs_bean.core.TransientBean.prototype.cljs$core$ITransientMap$_dissoc_BANG_$arity$2=function(a,b){if(this.editable_QMARK_)return delete this.obj[this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b)],this.__cnt=null,this;throw Error("dissoc! after persistent!");};
cljs_bean.core.TransientBean.prototype.call=function(a){switch(arguments.length-1){case 1:return this.cljs$core$IFn$_invoke$arity$1(arguments[1]);case 2:return this.cljs$core$IFn$_invoke$arity$2(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length-1)].join(""));}};cljs_bean.core.TransientBean.prototype.apply=function(a,b){return this.call.apply(this,[this].concat($APP.cljs.core.aclone(b)))};
cljs_bean.core.TransientBean.prototype.cljs$core$IFn$_invoke$arity$1=function(a){if(this.editable_QMARK_)return a=this.obj[this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(a):this.key__GT_prop.call(null,a)],this.recursive_QMARK_?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a;throw Error("lookup after persistent!");};
cljs_bean.core.TransientBean.prototype.cljs$core$IFn$_invoke$arity$2=function(a,b){if(this.editable_QMARK_)return a=cljs_bean.core.goog$module$goog$object.get(this.obj,this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(a):this.key__GT_prop.call(null,a),b),this.recursive_QMARK_&&a!==b?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a;throw Error("lookup after persistent!");};
cljs_bean.core.TransientBean.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,7,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[$APP.cljs.core.with_meta($APP.cljs$cst$77$editable_QMARK_,new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$78$tag,$APP.cljs$cst$79$boolean,$APP.cljs$cst$10$mutable,!0],null)),$APP.cljs$cst$177$obj,cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs.core.with_meta($APP.cljs$cst$2695$recursive_QMARK_,new $APP.cljs.core.PersistentArrayMap(null,
1,[$APP.cljs$cst$78$tag,$APP.cljs$cst$79$boolean],null)),$APP.cljs.core.with_meta(cljs$cst$4526$__cnt,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$10$mutable,!0],null))],null)};cljs_bean.core.TransientBean.cljs$lang$type=!0;cljs_bean.core.TransientBean.cljs$lang$ctorStr="cljs-bean.core/TransientBean";cljs_bean.core.TransientBean.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/TransientBean")};
cljs_bean.core.__GT_TransientBean=function(a,b,c,d,e,f,g){return new cljs_bean.core.TransientBean(a,b,c,d,e,f,g)};cljs_bean.core.BeanIterator=function(a,b,c,d,e,f,g,h){this.obj=a;this.prop__GT_key=b;this.key__GT_prop=c;this.transform=d;this.recursive_QMARK_=e;this.arr=f;this.i=g;this.cnt=h};cljs_bean.core.BeanIterator.prototype.hasNext=function(){return this.i<this.cnt};
cljs_bean.core.BeanIterator.prototype.next=function(){var a=cljs_bean.core.indexed_entry(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,this.i);this.i+=1;return a};
cljs_bean.core.BeanIterator.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,8,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[$APP.cljs$cst$177$obj,cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs.core.with_meta($APP.cljs$cst$2695$recursive_QMARK_,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$78$tag,$APP.cljs$cst$79$boolean],null)),$APP.cljs$cst$18$arr,$APP.cljs.core.with_meta($APP.cljs$cst$19$i,new $APP.cljs.core.PersistentArrayMap(null,
1,[$APP.cljs$cst$10$mutable,!0],null)),$APP.cljs$cst$59$cnt],null)};cljs_bean.core.BeanIterator.cljs$lang$type=!0;cljs_bean.core.BeanIterator.cljs$lang$ctorStr="cljs-bean.core/BeanIterator";cljs_bean.core.BeanIterator.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/BeanIterator")};cljs_bean.core.__GT_BeanIterator=function(a,b,c,d,e,f,g,h){return new cljs_bean.core.BeanIterator(a,b,c,d,e,f,g,h)};
cljs_bean.core.BeanSeq=function(a,b,c,d,e,f,g,h){this.obj=a;this.prop__GT_key=b;this.key__GT_prop=c;this.transform=d;this.recursive_QMARK_=e;this.arr=f;this.i=g;this.meta=h;this.cljs$lang$protocol_mask$partition0$=2179858686;this.cljs$lang$protocol_mask$partition1$=8192};cljs_bean.core.BeanSeq.prototype.toString=function(){return $APP.cljs.core.pr_str_STAR_(this)};cljs_bean.core.BeanSeq.prototype.equiv=function(a){return this.cljs$core$IEquiv$_equiv$arity$2(null,a)};
cljs_bean.core.BeanSeq.prototype.indexOf=function(){var a=null,b=function(d){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(this,d,0)},c=function(d,e){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(this,d,e)};a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return c.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};a.cljs$core$IFn$_invoke$arity$1=b;a.cljs$core$IFn$_invoke$arity$2=c;return a}();
cljs_bean.core.BeanSeq.prototype.lastIndexOf=function(){var a=null,b=function(d){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(this,d,$APP.cljs.core.count(this))},c=function(d,e){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(this,d,e)};a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return c.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};a.cljs$core$IFn$_invoke$arity$1=b;a.cljs$core$IFn$_invoke$arity$2=
c;return a}();cljs_bean.core.BeanSeq.prototype.cljs$core$IIndexed$_nth$arity$2=function(a,b){a=b+this.i;if(0<=a&&a<this.arr.length)return cljs_bean.core.indexed_entry(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,a);throw Error("Index out of bounds");};
cljs_bean.core.BeanSeq.prototype.cljs$core$IIndexed$_nth$arity$3=function(a,b,c){a=b+this.i;return 0<=a&&a<this.arr.length?cljs_bean.core.indexed_entry(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,a):c};cljs_bean.core.BeanSeq.prototype.cljs$core$IPrintWithWriter$_pr_writer$arity$3=function(a,b,c){return $APP.cljs.core.pr_sequential_writer(b,$APP.cljs.core.pr_writer,"("," ",")",c,this)};cljs_bean.core.BeanSeq.prototype.cljs$core$IMeta$_meta$arity$1=function(a){return this.meta};
cljs_bean.core.BeanSeq.prototype.cljs$core$ICloneable$_clone$arity$1=function(a){return new cljs_bean.core.BeanSeq(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,this.i,this.meta)};cljs_bean.core.BeanSeq.prototype.cljs$core$INext$_next$arity$1=function(a){return this.i+1<this.arr.length?new cljs_bean.core.BeanSeq(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,this.i+1,null):null};
cljs_bean.core.BeanSeq.prototype.cljs$core$ICounted$_count$arity$1=function(a){a=this.arr.length-this.i;return 0>a?0:a};cljs_bean.core.BeanSeq.prototype.cljs$core$IHash$_hash$arity$1=function(a){return $APP.cljs.core.hash_ordered_coll(this)};cljs_bean.core.BeanSeq.prototype.cljs$core$IEquiv$_equiv$arity$2=function(a,b){return cljs_bean.from.cljs.core.equiv_sequential(this,b)};cljs_bean.core.BeanSeq.prototype.cljs$core$IEmptyableCollection$_empty$arity$1=function(a){return $APP.cljs.core.List.EMPTY};
cljs_bean.core.BeanSeq.prototype.cljs$core$IReduce$_reduce$arity$2=function(a,b){return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$2(this,b)};cljs_bean.core.BeanSeq.prototype.cljs$core$IReduce$_reduce$arity$3=function(a,b,c){return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$3(this,b,c)};
cljs_bean.core.BeanSeq.prototype.cljs$core$ISeq$_first$arity$1=function(a){return cljs_bean.core.indexed_entry(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,this.i)};cljs_bean.core.BeanSeq.prototype.cljs$core$ISeq$_rest$arity$1=function(a){return this.i+1<this.arr.length?new cljs_bean.core.BeanSeq(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,this.i+1,null):$APP.cljs.core.List.EMPTY};
cljs_bean.core.BeanSeq.prototype.cljs$core$ISeqable$_seq$arity$1=function(a){return this};cljs_bean.core.BeanSeq.prototype.cljs$core$IWithMeta$_with_meta$arity$2=function(a,b){return b===this.meta?this:new cljs_bean.core.BeanSeq(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.arr,this.i,b)};cljs_bean.core.BeanSeq.prototype.cljs$core$ICollection$_conj$arity$2=function(a,b){return $APP.cljs.core.cons(b,this)};
cljs_bean.core.BeanSeq.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,8,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[$APP.cljs$cst$177$obj,cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs.core.with_meta($APP.cljs$cst$2695$recursive_QMARK_,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$78$tag,$APP.cljs$cst$79$boolean],null)),$APP.cljs$cst$18$arr,$APP.cljs$cst$19$i,$APP.cljs$cst$20$meta],null)};
cljs_bean.core.BeanSeq.cljs$lang$type=!0;cljs_bean.core.BeanSeq.cljs$lang$ctorStr="cljs-bean.core/BeanSeq";cljs_bean.core.BeanSeq.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/BeanSeq")};cljs_bean.core.__GT_BeanSeq=function(a,b,c,d,e,f,g,h){return new cljs_bean.core.BeanSeq(a,b,c,d,e,f,g,h)};
cljs_bean.core.Bean=function(a,b,c,d,e,f,g,h,k){this.meta=a;this.obj=b;this.prop__GT_key=c;this.key__GT_prop=d;this.transform=e;this.recursive_QMARK_=f;this.__arr=g;this.__cnt=h;this.__hash=k;this.cljs$lang$protocol_mask$partition0$=2164131599;this.cljs$lang$protocol_mask$partition1$=139268};cljs_bean.core.Bean.prototype.cljs$core$IFind$=$APP.cljs.core.PROTOCOL_SENTINEL;
cljs_bean.core.Bean.prototype.cljs$core$IFind$_find$arity$2=function(a,b){var c=cljs_bean.core.goog$module$goog$object.get(this.obj,this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b),cljs_bean.core.lookup_sentinel);if(c===cljs_bean.core.lookup_sentinel)return null;a=$APP.cljs.core.MapEntry;c=this.recursive_QMARK_?cljs_bean.core.__GT_val(c,this.prop__GT_key,this.key__GT_prop,this.transform):c;return new a(b,c,null)};
cljs_bean.core.Bean.prototype.toString=function(){return $APP.cljs.core.pr_str_STAR_(this)};cljs_bean.core.Bean.prototype.equiv=function(a){return this.cljs$core$IEquiv$_equiv$arity$2(null,a)};cljs_bean.core.Bean.prototype.keys=function(){return $APP.cljs.core.es6_iterator($APP.cljs.core.keys(this))};cljs_bean.core.Bean.prototype.entries=function(){return $APP.cljs.core.es6_entries_iterator($APP.cljs.core.seq(this))};cljs_bean.core.Bean.prototype.values=function(){return $APP.cljs.core.es6_iterator($APP.cljs.core.vals(this))};
cljs_bean.core.Bean.prototype.has=function(a){return $APP.cljs.core.contains_QMARK_(this,a)};cljs_bean.core.Bean.prototype.get=function(a,b){return this.cljs$core$ILookup$_lookup$arity$3(null,a,b)};
cljs_bean.core.Bean.prototype.forEach=function(a){for(var b=$APP.cljs.core.seq(this),c=null,d=0,e=0;;)if(e<d){var f=c.cljs$core$IIndexed$_nth$arity$2(null,e),g=$APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$3(f,0,null);f=$APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$3(f,1,null);a.cljs$core$IFn$_invoke$arity$2?a.cljs$core$IFn$_invoke$arity$2(f,g):a.call(null,f,g);e+=1}else if(b=$APP.cljs.core.seq(b))$APP.cljs.core.chunked_seq_QMARK_(b)?(c=$APP.cljs.core.chunk_first(b),b=$APP.cljs.core.chunk_rest(b),
g=c,d=$APP.cljs.core.count(c),c=g):(c=$APP.cljs.core.first(b),g=$APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$3(c,0,null),f=$APP.cljs.core.nth.cljs$core$IFn$_invoke$arity$3(c,1,null),a.cljs$core$IFn$_invoke$arity$2?a.cljs$core$IFn$_invoke$arity$2(f,g):a.call(null,f,g),b=$APP.cljs.core.next(b),c=null,d=0),e=0;else return null};
cljs_bean.core.Bean.prototype.cljs$core$ILookup$_lookup$arity$2=function(a,b){a=this.obj[this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b)];return this.recursive_QMARK_?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a};
cljs_bean.core.Bean.prototype.cljs$core$ILookup$_lookup$arity$3=function(a,b,c){a=cljs_bean.core.goog$module$goog$object.get(this.obj,this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b),c);return this.recursive_QMARK_&&a!==c?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a};
cljs_bean.core.Bean.prototype.cljs$core$IKVReduce$_kv_reduce$arity$3=function(a,b,c){var d=this;try{var e=$APP.cljs.core.volatile_BANG_(c);cljs_bean.core.goog$module$goog$object.forEach(d.obj,function(f,g,h){h=e.cljs$core$IVolatile$_vreset_BANG_$arity$2;var k=e.cljs$core$IDeref$_deref$arity$1(null);g=d.prop__GT_key.cljs$core$IFn$_invoke$arity$1?d.prop__GT_key.cljs$core$IFn$_invoke$arity$1(g):d.prop__GT_key.call(null,g);f=d.recursive_QMARK_?cljs_bean.core.__GT_val(f,d.prop__GT_key,d.key__GT_prop,d.transform):
f;f=b.cljs$core$IFn$_invoke$arity$3?b.cljs$core$IFn$_invoke$arity$3(k,g,f):b.call(null,k,g,f);h=h.call(e,null,f);if($APP.cljs.core.reduced_QMARK_(h))throw h;return null});return $APP.cljs.core.deref(e)}catch(f){a=f;if($APP.cljs.core.reduced_QMARK_(a))return $APP.cljs.core.deref(a);throw a;}};cljs_bean.core.Bean.prototype.cljs$core$IPrintWithWriter$_pr_writer$arity$3=function(a,b,c){return $APP.cljs.core.print_map(this,$APP.cljs.core.pr_writer,b,c)};
cljs_bean.core.Bean.prototype.cljs$core$IIterable$_iterator$arity$1=function(a){this.__arr==null&&(this.__arr=$APP.cljs.core.js_keys(this.obj));return new cljs_bean.core.BeanIterator(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.__arr,0,this.cljs$core$ICounted$_count$arity$1(null))};cljs_bean.core.Bean.prototype.cljs$core$IMeta$_meta$arity$1=function(a){return this.meta};
cljs_bean.core.Bean.prototype.cljs$core$ICloneable$_clone$arity$1=function(a){return new cljs_bean.core.Bean(this.meta,this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.__arr,this.__cnt,this.__hash)};cljs_bean.core.Bean.prototype.cljs$core$ICounted$_count$arity$1=function(a){return this.__cnt==null?(this.__arr==null&&(this.__arr=$APP.cljs.core.js_keys(this.obj)),this.__cnt=this.__arr.length):this.__cnt};
cljs_bean.core.Bean.prototype.cljs$core$IHash$_hash$arity$1=function(a){a=this.__hash;return a!=null?a:this.__hash=a=$APP.cljs.core.hash_unordered_coll(this)};cljs_bean.core.Bean.prototype.cljs$core$IEquiv$_equiv$arity$2=function(a,b){return $APP.cljs.core.equiv_map(this,b)};
cljs_bean.core.Bean.prototype.cljs$core$IEditableCollection$_as_transient$arity$1=function(a){return new cljs_bean.core.TransientBean(!0,cljs_bean.core.goog$module$goog$object.clone(this.obj),this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.__cnt)};cljs_bean.core.Bean.prototype.cljs$core$IEmptyableCollection$_empty$arity$1=function(a){return new cljs_bean.core.Bean(this.meta,{},this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,[],0,null)};
cljs_bean.core.Bean.prototype.cljs$core$IReduce$_reduce$arity$2=function(a,b){return $APP.cljs.core._reduce(this.cljs$core$ISeqable$_seq$arity$1(null),b)};cljs_bean.core.Bean.prototype.cljs$core$IReduce$_reduce$arity$3=function(a,b,c){return this.cljs$core$IKVReduce$_kv_reduce$arity$3(null,function(d,e,f){e=new $APP.cljs.core.MapEntry(e,f,null);return b.cljs$core$IFn$_invoke$arity$2?b.cljs$core$IFn$_invoke$arity$2(d,e):b.call(null,d,e)},c)};
cljs_bean.core.Bean.prototype.cljs$core$IMap$_dissoc$arity$2=function(a,b){a=cljs_bean.core.Bean;var c=this.meta,d=cljs_bean.core.goog$module$goog$object.clone(this.obj);delete d[this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):this.key__GT_prop.call(null,b)];return new a(c,d,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,null,null,null)};
cljs_bean.core.Bean.prototype.cljs$core$IAssociative$_assoc$arity$3=function(a,b,c){if(cljs_bean.core.snapshot_QMARK_(b,c,this.prop__GT_key,this.recursive_QMARK_))c=$APP.cljs.core._assoc($APP.cljs.core.with_meta(cljs_bean.core.snapshot(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_),this.meta),b,c);else{a=cljs_bean.core.Bean;var d=this.meta,e=cljs_bean.core.goog$module$goog$object.clone(this.obj);b=this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(b):
this.key__GT_prop.call(null,b);c=this.recursive_QMARK_?cljs_bean.core.unwrap(c):c;e[b]=c;c=new a(d,e,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,null,null,null)}return c};cljs_bean.core.Bean.prototype.cljs$core$IAssociative$_contains_key_QMARK_$arity$2=function(a,b){return this.cljs$core$ILookup$_lookup$arity$3(null,b,cljs_bean.core.lookup_sentinel)!==cljs_bean.core.lookup_sentinel};
cljs_bean.core.Bean.prototype.cljs$core$ISeqable$_seq$arity$1=function(a){this.__arr==null&&(this.__arr=$APP.cljs.core.js_keys(this.obj));return this.__arr.length>0?new cljs_bean.core.BeanSeq(this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.__arr,0,null):null};
cljs_bean.core.Bean.prototype.cljs$core$IWithMeta$_with_meta$arity$2=function(a,b){return b===this.meta?this:new cljs_bean.core.Bean(b,this.obj,this.prop__GT_key,this.key__GT_prop,this.transform,this.recursive_QMARK_,this.__arr,this.__cnt,this.__hash)};cljs_bean.core.Bean.prototype.cljs$core$ICollection$_conj$arity$2=function(a,b){return cljs_bean.from.cljs.core.PersistentArrayMap_conj(this,b)};
cljs_bean.core.Bean.prototype.call=function(a){switch(arguments.length-1){case 1:return this.cljs$core$IFn$_invoke$arity$1(arguments[1]);case 2:return this.cljs$core$IFn$_invoke$arity$2(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length-1)].join(""));}};cljs_bean.core.Bean.prototype.apply=function(a,b){return this.call.apply(this,[this].concat($APP.cljs.core.aclone(b)))};
cljs_bean.core.Bean.prototype.cljs$core$IFn$_invoke$arity$1=function(a){a=this.obj[this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(a):this.key__GT_prop.call(null,a)];return this.recursive_QMARK_?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a};
cljs_bean.core.Bean.prototype.cljs$core$IFn$_invoke$arity$2=function(a,b){a=cljs_bean.core.goog$module$goog$object.get(this.obj,this.key__GT_prop.cljs$core$IFn$_invoke$arity$1?this.key__GT_prop.cljs$core$IFn$_invoke$arity$1(a):this.key__GT_prop.call(null,a),b);return this.recursive_QMARK_&&a!==b?cljs_bean.core.__GT_val(a,this.prop__GT_key,this.key__GT_prop,this.transform):a};
cljs_bean.core.Bean.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,9,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[$APP.cljs$cst$20$meta,$APP.cljs$cst$177$obj,cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs.core.with_meta($APP.cljs$cst$2695$recursive_QMARK_,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$78$tag,$APP.cljs$cst$79$boolean],null)),$APP.cljs.core.with_meta(cljs$cst$4527$__arr,new $APP.cljs.core.PersistentArrayMap(null,
1,[$APP.cljs$cst$10$mutable,!0],null)),$APP.cljs.core.with_meta(cljs$cst$4526$__cnt,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$10$mutable,!0],null)),$APP.cljs.core.with_meta($APP.cljs$cst$26$__hash,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$10$mutable,!0],null))],null)};cljs_bean.core.Bean.cljs$lang$type=!0;cljs_bean.core.Bean.cljs$lang$ctorStr="cljs-bean.core/Bean";cljs_bean.core.Bean.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/Bean")};
cljs_bean.core.__GT_Bean=function(a,b,c,d,e,f,g,h,k){return new cljs_bean.core.Bean(a,b,c,d,e,f,g,h,k)};cljs_bean.core.TransientArrayVector=function(a,b,c,d,e){this.editable_QMARK_=a;this.arr=b;this.prop__GT_key=c;this.key__GT_prop=d;this.transform=e;this.cljs$lang$protocol_mask$partition1$=88;this.cljs$lang$protocol_mask$partition0$=275};
cljs_bean.core.TransientArrayVector.prototype.cljs$core$ITransientCollection$_conj_BANG_$arity$2=function(a,b){if(this.editable_QMARK_)return cljs_bean.core.compatible_value_QMARK_(b,!0)?(this.arr.push(cljs_bean.core.unwrap(b)),this):$APP.cljs.core._conj_BANG_($APP.cljs.core.transient$(cljs_bean.core.snapshot_arr(this.arr)),b);throw Error("conj! after persistent!");};
cljs_bean.core.TransientArrayVector.prototype.cljs$core$ITransientCollection$_persistent_BANG_$arity$1=function(a){if(this.editable_QMARK_)return this.editable_QMARK_=!1,new cljs_bean.core.ArrayVector(null,this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,null);throw Error("persistent! called twice");};cljs_bean.core.TransientArrayVector.prototype.cljs$core$ITransientAssociative$_assoc_BANG_$arity$3=function(a,b,c){return cljs_bean.from.cljs.core.TransientVector_assoc_BANG_(this,b,c,"TransientArrayVector")};
cljs_bean.core.TransientArrayVector.prototype.cljs$core$ITransientVector$_assoc_n_BANG_$arity$3=function(a,b,c){if(this.editable_QMARK_){if(cljs_bean.core.compatible_value_QMARK_(c,!0)){if(0<=b&&b<this.arr.length)return this.arr[b]=cljs_bean.core.unwrap(c),this;if(b===this.arr.length)return this.cljs$core$ITransientCollection$_conj_BANG_$arity$2(null,c);throw Error(["Index ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(b)," out of bounds for TransientArrayVector of length",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(this.arr.length)].join(""));
}return $APP.cljs.core._assoc_n_BANG_($APP.cljs.core.transient$(cljs_bean.core.snapshot_arr(this.arr)),b,c)}throw Error("assoc! after persistent!");};cljs_bean.core.TransientArrayVector.prototype.cljs$core$ITransientVector$_pop_BANG_$arity$1=function(a){if(this.editable_QMARK_){if(this.arr.length===0)throw Error("Can't pop empty vector");this.arr=this.arr.slice(0,this.arr.length-1);return this}throw Error("pop! after persistent!");};
cljs_bean.core.TransientArrayVector.prototype.cljs$core$ICounted$_count$arity$1=function(a){if(this.editable_QMARK_)return this.arr.length;throw Error("count after persistent!");};cljs_bean.core.TransientArrayVector.prototype.cljs$core$IIndexed$_nth$arity$2=function(a,b){if(this.editable_QMARK_)return cljs_bean.core.__GT_val(this.arr[b],this.prop__GT_key,this.key__GT_prop,this.transform);throw Error("nth after persistent!");};
cljs_bean.core.TransientArrayVector.prototype.cljs$core$IIndexed$_nth$arity$3=function(a,b,c){return 0<=b&&b<this.arr.length?this.cljs$core$IIndexed$_nth$arity$2(null,b):c};cljs_bean.core.TransientArrayVector.prototype.cljs$core$ILookup$_lookup$arity$2=function(a,b){return this.cljs$core$ILookup$_lookup$arity$3(null,b,null)};cljs_bean.core.TransientArrayVector.prototype.cljs$core$ILookup$_lookup$arity$3=function(a,b,c){return typeof b==="number"?this.cljs$core$IIndexed$_nth$arity$3(null,b,c):c};
cljs_bean.core.TransientArrayVector.prototype.call=function(a){switch(arguments.length-1){case 1:return this.cljs$core$IFn$_invoke$arity$1(arguments[1]);case 2:return this.cljs$core$IFn$_invoke$arity$2(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length-1)].join(""));}};cljs_bean.core.TransientArrayVector.prototype.apply=function(a,b){return this.call.apply(this,[this].concat($APP.cljs.core.aclone(b)))};
cljs_bean.core.TransientArrayVector.prototype.cljs$core$IFn$_invoke$arity$1=function(a){return this.cljs$core$ILookup$_lookup$arity$2(null,a)};cljs_bean.core.TransientArrayVector.prototype.cljs$core$IFn$_invoke$arity$2=function(a,b){return this.cljs$core$ILookup$_lookup$arity$3(null,a,b)};
cljs_bean.core.TransientArrayVector.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,5,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[$APP.cljs.core.with_meta($APP.cljs$cst$77$editable_QMARK_,new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$78$tag,$APP.cljs$cst$79$boolean,$APP.cljs$cst$10$mutable,!0],null)),$APP.cljs.core.with_meta($APP.cljs$cst$18$arr,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$10$mutable,!0],null)),cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,
cljs$cst$4525$transform],null)};cljs_bean.core.TransientArrayVector.cljs$lang$type=!0;cljs_bean.core.TransientArrayVector.cljs$lang$ctorStr="cljs-bean.core/TransientArrayVector";cljs_bean.core.TransientArrayVector.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/TransientArrayVector")};cljs_bean.core.__GT_TransientArrayVector=function(a,b,c,d,e){return new cljs_bean.core.TransientArrayVector(a,b,c,d,e)};
cljs_bean.core.ArrayVectorIterator=function(a,b,c,d,e,f){this.prop__GT_key=a;this.key__GT_prop=b;this.transform=c;this.arr=d;this.i=e;this.cnt=f};cljs_bean.core.ArrayVectorIterator.prototype.hasNext=function(){return this.i<this.cnt};cljs_bean.core.ArrayVectorIterator.prototype.next=function(){var a=cljs_bean.core.__GT_val(this.arr[this.i],this.prop__GT_key,this.key__GT_prop,this.transform);this.i+=1;return a};
cljs_bean.core.ArrayVectorIterator.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,6,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs$cst$18$arr,$APP.cljs.core.with_meta($APP.cljs$cst$19$i,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$10$mutable,!0],null)),$APP.cljs$cst$59$cnt],null)};cljs_bean.core.ArrayVectorIterator.cljs$lang$type=!0;
cljs_bean.core.ArrayVectorIterator.cljs$lang$ctorStr="cljs-bean.core/ArrayVectorIterator";cljs_bean.core.ArrayVectorIterator.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/ArrayVectorIterator")};cljs_bean.core.__GT_ArrayVectorIterator=function(a,b,c,d,e,f){return new cljs_bean.core.ArrayVectorIterator(a,b,c,d,e,f)};
cljs_bean.core.ArrayVectorSeq=function(a,b,c,d,e,f){this.prop__GT_key=a;this.key__GT_prop=b;this.transform=c;this.arr=d;this.i=e;this.meta=f;this.cljs$lang$protocol_mask$partition0$=2179858686;this.cljs$lang$protocol_mask$partition1$=8192};cljs_bean.core.ArrayVectorSeq.prototype.toString=function(){return $APP.cljs.core.pr_str_STAR_(this)};cljs_bean.core.ArrayVectorSeq.prototype.equiv=function(a){return this.cljs$core$IEquiv$_equiv$arity$2(null,a)};
cljs_bean.core.ArrayVectorSeq.prototype.indexOf=function(){var a=null,b=function(d){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(this,d,0)},c=function(d,e){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(this,d,e)};a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return c.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};a.cljs$core$IFn$_invoke$arity$1=b;a.cljs$core$IFn$_invoke$arity$2=c;return a}();
cljs_bean.core.ArrayVectorSeq.prototype.lastIndexOf=function(){var a=null,b=function(d){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(this,d,$APP.cljs.core.count(this))},c=function(d,e){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(this,d,e)};a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return c.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};a.cljs$core$IFn$_invoke$arity$1=b;a.cljs$core$IFn$_invoke$arity$2=
c;return a}();cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IIndexed$_nth$arity$2=function(a,b){a=b+this.i;if(0<=a&&a<this.arr.length)return cljs_bean.core.__GT_val(this.arr[a],this.prop__GT_key,this.key__GT_prop,this.transform);throw Error("Index out of bounds");};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IIndexed$_nth$arity$3=function(a,b,c){a=b+this.i;return 0<=a&&a<this.arr.length?cljs_bean.core.__GT_val(this.arr[a],this.prop__GT_key,this.key__GT_prop,this.transform):c};
cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IPrintWithWriter$_pr_writer$arity$3=function(a,b,c){return $APP.cljs.core.pr_sequential_writer(b,$APP.cljs.core.pr_writer,"("," ",")",c,this)};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IMeta$_meta$arity$1=function(a){return this.meta};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$ICloneable$_clone$arity$1=function(a){return new cljs_bean.core.ArrayVectorSeq(this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,this.i,this.meta)};
cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$INext$_next$arity$1=function(a){return this.i+1<this.arr.length?new cljs_bean.core.ArrayVectorSeq(this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,this.i+1,null):null};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$ICounted$_count$arity$1=function(a){a=this.arr.length-this.i;return 0>a?0:a};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IHash$_hash$arity$1=function(a){return $APP.cljs.core.hash_ordered_coll(this)};
cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IEquiv$_equiv$arity$2=function(a,b){return cljs_bean.from.cljs.core.equiv_sequential(this,b)};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IEmptyableCollection$_empty$arity$1=function(a){return $APP.cljs.core.List.EMPTY};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IReduce$_reduce$arity$2=function(a,b){return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$2(this,b)};
cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IReduce$_reduce$arity$3=function(a,b,c){return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$3(this,b,c)};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$ISeq$_first$arity$1=function(a){return cljs_bean.core.__GT_val(this.arr[this.i],this.prop__GT_key,this.key__GT_prop,this.transform)};
cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$ISeq$_rest$arity$1=function(a){return this.i+1<this.arr.length?new cljs_bean.core.ArrayVectorSeq(this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,this.i+1,null):$APP.cljs.core.List.EMPTY};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$ISeqable$_seq$arity$1=function(a){return this};
cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$IWithMeta$_with_meta$arity$2=function(a,b){return b===this.meta?this:new cljs_bean.core.ArrayVectorSeq(this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,this.i,b)};cljs_bean.core.ArrayVectorSeq.prototype.cljs$core$ICollection$_conj$arity$2=function(a,b){return $APP.cljs.core.cons(b,this)};
cljs_bean.core.ArrayVectorSeq.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,6,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs$cst$18$arr,$APP.cljs$cst$19$i,$APP.cljs$cst$20$meta],null)};cljs_bean.core.ArrayVectorSeq.cljs$lang$type=!0;cljs_bean.core.ArrayVectorSeq.cljs$lang$ctorStr="cljs-bean.core/ArrayVectorSeq";
cljs_bean.core.ArrayVectorSeq.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/ArrayVectorSeq")};cljs_bean.core.__GT_ArrayVectorSeq=function(a,b,c,d,e,f){return new cljs_bean.core.ArrayVectorSeq(a,b,c,d,e,f)};cljs_bean.core.ArrayVector=function(a,b,c,d,e,f){this.meta=a;this.prop__GT_key=b;this.key__GT_prop=c;this.transform=d;this.arr=e;this.__hash=f;this.cljs$lang$protocol_mask$partition0$=2315150111;this.cljs$lang$protocol_mask$partition1$=141316};
cljs_bean.core.ArrayVector.prototype.cljs$core$IFind$=$APP.cljs.core.PROTOCOL_SENTINEL;cljs_bean.core.ArrayVector.prototype.cljs$core$IFind$_find$arity$2=function(a,b){return 0<=b&&b<this.arr.length?new $APP.cljs.core.MapEntry(b,cljs_bean.core.__GT_val(this.arr[b],this.prop__GT_key,this.key__GT_prop,this.transform),null):null};cljs_bean.core.ArrayVector.prototype.toString=function(){return $APP.cljs.core.pr_str_STAR_(this)};
cljs_bean.core.ArrayVector.prototype.equiv=function(a){return this.cljs$core$IEquiv$_equiv$arity$2(null,a)};
cljs_bean.core.ArrayVector.prototype.indexOf=function(){var a=null,b=function(d){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(this,d,0)},c=function(d,e){return cljs_bean.from.cljs.core._indexOf.cljs$core$IFn$_invoke$arity$3(this,d,e)};a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return c.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};a.cljs$core$IFn$_invoke$arity$1=b;a.cljs$core$IFn$_invoke$arity$2=c;return a}();
cljs_bean.core.ArrayVector.prototype.lastIndexOf=function(){var a=null,b=function(d){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$2(this,d)},c=function(d,e){return cljs_bean.from.cljs.core._lastIndexOf.cljs$core$IFn$_invoke$arity$3(this,d,e)};a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return c.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};a.cljs$core$IFn$_invoke$arity$1=b;a.cljs$core$IFn$_invoke$arity$2=c;return a}();
cljs_bean.core.ArrayVector.prototype.cljs$core$ILookup$_lookup$arity$2=function(a,b){return this.cljs$core$ILookup$_lookup$arity$3(null,b,null)};cljs_bean.core.ArrayVector.prototype.cljs$core$ILookup$_lookup$arity$3=function(a,b,c){return cljs_bean.from.cljs.core.PersistentVector_lookup(this,b,c)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IKVReduce$_kv_reduce$arity$3=function(a,b,c){a=0;for(var d=c;;)if(a<this.arr.length){c=this.arr.length;var e;a:{for(e=0;;)if(e<c){var f=e+a,g=cljs_bean.core.__GT_val(this.arr[e],this.prop__GT_key,this.key__GT_prop,this.transform);d=b.cljs$core$IFn$_invoke$arity$3?b.cljs$core$IFn$_invoke$arity$3(d,f,g):b.call(null,d,f,g);if($APP.cljs.core.reduced_QMARK_(d)){e=d;break a}e+=1}else{e=d;break a}e=void 0}if($APP.cljs.core.reduced_QMARK_(e))return $APP.cljs.core.deref(e);
a+=c;d=e}else return d};cljs_bean.core.ArrayVector.prototype.cljs$core$IIndexed$_nth$arity$2=function(a,b){if(0<=b&&b<this.arr.length)return cljs_bean.core.__GT_val(this.arr[b],this.prop__GT_key,this.key__GT_prop,this.transform);throw Error(["No item ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(b)," in vector of length ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(this.arr.length)].join(""));};
cljs_bean.core.ArrayVector.prototype.cljs$core$IIndexed$_nth$arity$3=function(a,b,c){return 0<=b&&b<this.arr.length?cljs_bean.core.__GT_val(this.arr[b],this.prop__GT_key,this.key__GT_prop,this.transform):c};cljs_bean.core.ArrayVector.prototype.cljs$core$IPrintWithWriter$_pr_writer$arity$3=function(a,b,c){return $APP.cljs.core.pr_sequential_writer(b,$APP.cljs.core.pr_writer,"["," ","]",c,this)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IVector$_assoc_n$arity$3=function(a,b,c){if(0<=b&&b<this.arr.length)return cljs_bean.core.compatible_value_QMARK_(c,!0)?(a=$APP.cljs.core.aclone(this.arr),a[b]=cljs_bean.core.unwrap(c),new cljs_bean.core.ArrayVector(this.meta,this.prop__GT_key,this.key__GT_prop,this.transform,a,null)):$APP.cljs.core._assoc_n(cljs_bean.core.snapshot_arr(this.arr),b,c);if(b===this.arr.length)return this.cljs$core$ICollection$_conj$arity$2(null,c);throw Error(["Index ",
$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(b)," out of bounds  [0,",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(this.arr.length),"]"].join(""));};cljs_bean.core.ArrayVector.prototype.cljs$core$IIterable$_iterator$arity$1=function(a){return new cljs_bean.core.ArrayVectorIterator(this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,0,this.arr.length)};cljs_bean.core.ArrayVector.prototype.cljs$core$IMeta$_meta$arity$1=function(a){return this.meta};
cljs_bean.core.ArrayVector.prototype.cljs$core$ICloneable$_clone$arity$1=function(a){return new cljs_bean.core.ArrayVector(this.meta,this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,this.__hash)};cljs_bean.core.ArrayVector.prototype.cljs$core$ICounted$_count$arity$1=function(a){return this.arr.length};cljs_bean.core.ArrayVector.prototype.cljs$core$IStack$_peek$arity$1=function(a){return this.arr.length>0?this.cljs$core$IIndexed$_nth$arity$2(null,this.arr.length-1):null};
cljs_bean.core.ArrayVector.prototype.cljs$core$IStack$_pop$arity$1=function(a){if(this.arr.length===0)throw Error("Can't pop empty vector");if(1===this.arr.length)return this.cljs$core$IEmptyableCollection$_empty$arity$1(null);a=$APP.cljs.core.aclone(this.arr);return new cljs_bean.core.ArrayVector(this.meta,this.prop__GT_key,this.key__GT_prop,this.transform,a.slice(0,a.length-1),null)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IReversible$_rseq$arity$1=function(a){return this.arr.length>0?new $APP.cljs.core.RSeq(this,this.arr.length-1,null):null};cljs_bean.core.ArrayVector.prototype.cljs$core$IHash$_hash$arity$1=function(a){a=this.__hash;return a!=null?a:this.__hash=a=$APP.cljs.core.hash_ordered_coll(this)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IEquiv$_equiv$arity$2=function(a,b){return cljs_bean.from.cljs.core.PersistentVector_equiv(this,b,cljs_bean.core.ArrayVector,this.arr.length)};cljs_bean.core.ArrayVector.prototype.cljs$core$IEditableCollection$_as_transient$arity$1=function(a){return new cljs_bean.core.TransientArrayVector(!0,$APP.cljs.core.aclone(this.arr),this.prop__GT_key,this.key__GT_prop,this.transform)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IEmptyableCollection$_empty$arity$1=function(a){return new cljs_bean.core.ArrayVector(this.meta,this.prop__GT_key,this.key__GT_prop,this.transform,[],null)};cljs_bean.core.ArrayVector.prototype.cljs$core$IReduce$_reduce$arity$2=function(a,b){return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$2(this,b)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IReduce$_reduce$arity$3=function(a,b,c){return cljs_bean.from.cljs.core.ci_reduce.cljs$core$IFn$_invoke$arity$3(this,b,c)};cljs_bean.core.ArrayVector.prototype.cljs$core$IAssociative$_assoc$arity$3=function(a,b,c){return cljs_bean.from.cljs.core.PersistentVector_assoc(this,b,c)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IAssociative$_contains_key_QMARK_$arity$2=function(a,b){return cljs_bean.from.cljs.core.PersistentVector_contains_key_QMARK_(this,b,this.arr.length)};cljs_bean.core.ArrayVector.prototype.cljs$core$ISeqable$_seq$arity$1=function(a){return this.arr.length>0?new cljs_bean.core.ArrayVectorSeq(this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,0,null):null};
cljs_bean.core.ArrayVector.prototype.cljs$core$IWithMeta$_with_meta$arity$2=function(a,b){return b===this.meta?this:new cljs_bean.core.ArrayVector(b,this.prop__GT_key,this.key__GT_prop,this.transform,this.arr,this.__hash)};
cljs_bean.core.ArrayVector.prototype.cljs$core$ICollection$_conj$arity$2=function(a,b){return cljs_bean.core.compatible_value_QMARK_(b,!0)?(a=$APP.cljs.core.aclone(this.arr),a[a.length]=cljs_bean.core.unwrap(b),new cljs_bean.core.ArrayVector(this.meta,this.prop__GT_key,this.key__GT_prop,this.transform,a,null)):$APP.cljs.core._conj(cljs_bean.core.snapshot_arr(this.arr),b)};
cljs_bean.core.ArrayVector.prototype.call=function(a){switch(arguments.length-1){case 1:return this.cljs$core$IFn$_invoke$arity$1(arguments[1]);case 2:return this.cljs$core$IFn$_invoke$arity$2(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length-1)].join(""));}};cljs_bean.core.ArrayVector.prototype.apply=function(a,b){return this.call.apply(this,[this].concat($APP.cljs.core.aclone(b)))};
cljs_bean.core.ArrayVector.prototype.cljs$core$IFn$_invoke$arity$1=function(a){return this.cljs$core$IIndexed$_nth$arity$2(null,a)};cljs_bean.core.ArrayVector.prototype.cljs$core$IFn$_invoke$arity$2=function(a,b){return this.cljs$core$IIndexed$_nth$arity$3(null,a,b)};
cljs_bean.core.ArrayVector.prototype.cljs$core$IComparable$_compare$arity$2=function(a,b){if($APP.cljs.core.vector_QMARK_(b))return cljs_bean.from.cljs.core.compare_indexed.cljs$core$IFn$_invoke$arity$2(this,b);throw Error(["Cannot compare ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(this)," to ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(b)].join(""));};
cljs_bean.core.ArrayVector.getBasis=function(){return new $APP.cljs.core.PersistentVector(null,6,5,$APP.cljs.core.PersistentVector.EMPTY_NODE,[$APP.cljs$cst$20$meta,cljs$cst$4523$prop__GT_key,cljs$cst$4524$key__GT_prop,cljs$cst$4525$transform,$APP.cljs$cst$18$arr,$APP.cljs.core.with_meta($APP.cljs$cst$26$__hash,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$10$mutable,!0],null))],null)};cljs_bean.core.ArrayVector.cljs$lang$type=!0;cljs_bean.core.ArrayVector.cljs$lang$ctorStr="cljs-bean.core/ArrayVector";
cljs_bean.core.ArrayVector.cljs$lang$ctorPrWriter=function(a,b,c){return $APP.cljs.core._write(b,"cljs-bean.core/ArrayVector")};cljs_bean.core.__GT_ArrayVector=function(a,b,c,d,e,f){return new cljs_bean.core.ArrayVector(a,b,c,d,e,f)};cljs_bean.core.default_key__GT_prop=function(a){return a instanceof $APP.cljs.core.Keyword?a.fqn:null};
cljs_bean.core.bean=function(a){switch(arguments.length){case 0:return cljs_bean.core.bean.cljs$core$IFn$_invoke$arity$0();case 1:return cljs_bean.core.bean.cljs$core$IFn$_invoke$arity$1(arguments[0]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=1<b.length?new $APP.cljs.core.IndexedSeq(b.slice(1),0,null):null;return cljs_bean.core.bean.cljs$core$IFn$_invoke$arity$variadic(arguments[0],b)}};
cljs_bean.core.bean.cljs$core$IFn$_invoke$arity$0=function(){return new cljs_bean.core.Bean(null,{},$APP.cljs.core.keyword,cljs_bean.core.default_key__GT_prop,null,!1,[],0,null)};cljs_bean.core.bean.cljs$core$IFn$_invoke$arity$1=function(a){return new cljs_bean.core.Bean(null,a,$APP.cljs.core.keyword,cljs_bean.core.default_key__GT_prop,null,!1,null,null,null)};
cljs_bean.core.bean.cljs$core$IFn$_invoke$arity$variadic=function(a,b){var c=$APP.cljs.core.__destructure_map(b);b=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$127$keywordize_keys);var d=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,cljs$cst$4528$prop__GT_key),e=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,cljs$cst$4529$key__GT_prop),f=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$2102$transform);c=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,
cljs$cst$4530$recursive);return b===!1?new cljs_bean.core.Bean(null,a,$APP.cljs.core.identity,$APP.cljs.core.identity,f,$APP.cljs.core.boolean$(c),null,null,null):d!=null&&e!=null?new cljs_bean.core.Bean(null,a,d,e,f,$APP.cljs.core.boolean$(c),null,null,null):new cljs_bean.core.Bean(null,a,$APP.cljs.core.keyword,cljs_bean.core.default_key__GT_prop,f,$APP.cljs.core.boolean$(c),null,null,null)};
cljs_bean.core.bean.cljs$lang$applyTo=function(a){var b=$APP.cljs.core.first(a);a=$APP.cljs.core.next(a);return this.cljs$core$IFn$_invoke$arity$variadic(b,a)};cljs_bean.core.bean.cljs$lang$maxFixedArity=1;cljs_bean.core.bean_QMARK_=function(a){return a instanceof cljs_bean.core.Bean};cljs_bean.core.object=function(a){return a.obj};
cljs_bean.core.__GT_clj=function(a){switch(arguments.length){case 1:return cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1(arguments[0]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=1<b.length?new $APP.cljs.core.IndexedSeq(b.slice(1),0,null):null;return cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$variadic(arguments[0],b)}};
cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1=function(a){return cljs_bean.core.__GT_val(a,$APP.cljs.core.keyword,cljs_bean.core.default_key__GT_prop,null)};
cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$variadic=function(a,b){var c=$APP.cljs.core.__destructure_map(b);b=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$127$keywordize_keys);var d=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,cljs$cst$4528$prop__GT_key),e=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,cljs$cst$4529$key__GT_prop);c=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$2102$transform);return b===!1?cljs_bean.core.__GT_val(a,$APP.cljs.core.identity,
$APP.cljs.core.identity,c):d!=null&&e!=null?cljs_bean.core.__GT_val(a,d,e,c):cljs_bean.core.__GT_val(a,$APP.cljs.core.keyword,cljs_bean.core.default_key__GT_prop,c)};cljs_bean.core.__GT_clj.cljs$lang$applyTo=function(a){var b=$APP.cljs.core.first(a);a=$APP.cljs.core.next(a);return this.cljs$core$IFn$_invoke$arity$variadic(b,a)};cljs_bean.core.__GT_clj.cljs$lang$maxFixedArity=1;
cljs_bean.core.__GT_js=function(a){switch(arguments.length){case 1:return cljs_bean.core.__GT_js.cljs$core$IFn$_invoke$arity$1(arguments[0]);default:for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;b=1<b.length?new $APP.cljs.core.IndexedSeq(b.slice(1),0,null):null;return cljs_bean.core.__GT_js.cljs$core$IFn$_invoke$arity$variadic(arguments[0],b)}};
cljs_bean.core.__GT_js.cljs$core$IFn$_invoke$arity$1=function(a){return a instanceof cljs_bean.core.Bean?a.obj:a instanceof cljs_bean.core.ArrayVector?a.arr:$APP.cljs.core.clj__GT_js.cljs$core$IFn$_invoke$arity$variadic(a,$APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([$APP.cljs$cst$126$keyword_fn,cljs_bean.core.default_key__GT_prop],0))};
cljs_bean.core.__GT_js.cljs$core$IFn$_invoke$arity$variadic=function(a,b){if(a instanceof cljs_bean.core.Bean)return a.obj;if(a instanceof cljs_bean.core.ArrayVector)return a.arr;b=$APP.cljs.core.__destructure_map(b);b=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$3(b,cljs$cst$4529$key__GT_prop,cljs_bean.core.default_key__GT_prop);return $APP.cljs.core.clj__GT_js.cljs$core$IFn$_invoke$arity$variadic(a,$APP.cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([$APP.cljs$cst$126$keyword_fn,b],0))};
cljs_bean.core.__GT_js.cljs$lang$applyTo=function(a){var b=$APP.cljs.core.first(a);a=$APP.cljs.core.next(a);return this.cljs$core$IFn$_invoke$arity$variadic(b,a)};cljs_bean.core.__GT_js.cljs$lang$maxFixedArity=1;cljs_bean.core.set_empty_colls_BANG_=function(){$APP.cljs.core.PersistentArrayMap.EMPTY=cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1({});$APP.cljs.core.PersistentVector.EMPTY=cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1([]);return null};$APP.bb_web_ds_tools.workers.sci={};$APP.bb_web_ds_tools.workers.sci.datasets_atom=$APP.cljs.core.atom.cljs$core$IFn$_invoke$arity$1($APP.cljs.core.PersistentArrayMap.EMPTY);$APP.bb_web_ds_tools.workers.sci.datasets_sci_var=$APP.sci.core.new_var.cljs$core$IFn$_invoke$arity$2(cljs$cst$4531$datasets,$APP.bb_web_ds_tools.workers.sci.datasets_atom);$APP.bb_web_ds_tools.workers.sci._STAR_suppress_sync_STAR_=!1;
$APP.bb_web_ds_tools.workers.sci.post_msg=function(a){var b=$APP.cognitect.transit.writer.cljs$core$IFn$_invoke$arity$1($APP.cljs$cst$2467$json);a=$APP.cognitect.transit.write(b,$APP.cljs.core.seq(a)?a:"nil");return postMessage(a)};
$APP.cljs.core.add_watch($APP.bb_web_ds_tools.workers.sci.datasets_atom,cljs$cst$4532$sync_main,function(a,b,c,d){if($APP.cljs.core.truth_($APP.bb_web_ds_tools.workers.sci._STAR_suppress_sync_STAR_))return null;b=$APP.cljs.core.set($APP.cljs.core.keys(c));var e=$APP.cljs.core.set($APP.cljs.core.keys(d));a=$APP.clojure.set.difference.cljs$core$IFn$_invoke$arity$2(e,b);b=$APP.clojure.set.intersection.cljs$core$IFn$_invoke$arity$2(e,b);b=$APP.cljs.core.filter.cljs$core$IFn$_invoke$arity$2(function(f){return $APP.cljs.core.not_EQ_.cljs$core$IFn$_invoke$arity$2($APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,
f),$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(d,f))},b);a=$APP.cljs.core.select_keys(d,$APP.cljs.core.concat.cljs$core$IFn$_invoke$arity$2(a,b));return $APP.cljs.core.seq(a)?$APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,cljs$cst$4533$patch_datasets,$APP.cljs$cst$2926$patch,a],null)):null});
$APP.bb_web_ds_tools.workers.sci.sci_ctx=$APP.sci.core.init(new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$473$namespaces,new $APP.cljs.core.PersistentArrayMap(null,3,[$APP.cljs$cst$490$clojure_DOT_core,new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$981$println,function(){var a=function(c){return $APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,$APP.cljs$cst$2519$stdout,$APP.cljs$cst$2509$text,$APP.cljs.core.apply.cljs$core$IFn$_invoke$arity$2($APP.cljs.core.str,
$APP.cljs.core.interpose.cljs$core$IFn$_invoke$arity$2(" ",c))],null))},b=function(c){var d=null;if(arguments.length>0){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $APP.cljs.core.IndexedSeq(e,0,null)}return a.call(this,d)};b.cljs$lang$maxFixedArity=0;b.cljs$lang$applyTo=function(c){c=$APP.cljs.core.seq(c);return a(c)};b.cljs$core$IFn$_invoke$arity$variadic=a;return b}()],null),$APP.cljs$cst$2928$re_frame_DOT_core,new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$418$dispatch,
function(a){return $APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,$APP.cljs$cst$417$dispatch,$APP.cljs$cst$1638$event,a],null))},$APP.cljs$cst$2929$subscribe,function(a){return $APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,$APP.cljs$cst$2520$stderr,$APP.cljs$cst$2509$text,"rf/subscribe is not supported in the worker."],null))}],null),$APP.cljs$cst$489$user,new $APP.cljs.core.PersistentArrayMap(null,
1,[cljs$cst$4531$datasets,$APP.bb_web_ds_tools.workers.sci.datasets_sci_var],null)],null)],null));$APP.sci.core.eval_string_STAR_($APP.bb_web_ds_tools.workers.sci.sci_ctx,"(require '[clojure.string :as str] '[clojure.set :as set] '[clojure.edn :as edn])");
$APP.bb_web_ds_tools.workers.sci.prepare_for_transport=function(a){return a==null?a:typeof a==="number"?a:typeof a==="string"?a:$APP.cljs.core.boolean_QMARK_(a)?a:a instanceof $APP.cljs.core.Keyword?a:a instanceof $APP.cljs.core.Symbol?a:$APP.cljs.core.uuid_QMARK_(a)?a:$APP.cljs.core.inst_QMARK_(a)?a:$APP.cljs.core.coll_QMARK_(a)?a:$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(a)};
$APP.bb_web_ds_tools.workers.sci.eval_code=function(a){if($APP.cljs.core.seq(a)){a=$APP.cljs.tools.reader.reader_types.string_push_back_reader.cljs$core$IFn$_invoke$arity$1(a);try{for(var b=$APP.cljs.core.PersistentVector.EMPTY;;){try{var c=$APP.cljs.tools.reader.read.cljs$core$IFn$_invoke$arity$3(a,!1,$APP.cljs$cst$226$eof)}catch(l){c=new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$1524$error,["Read Error: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(l)].join("")],null)}if($APP.cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(c,
$APP.cljs$cst$226$eof))return b;var d=$APP.cljs.core,e=d.truth_,f=$APP.cljs.core.map_QMARK_(c);var g=f?$APP.cljs$cst$1524$error.cljs$core$IFn$_invoke$arity$1(c):f;if(e.call(d,g))$APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,$APP.cljs$cst$1524$error,$APP.cljs$cst$2509$text,$APP.cljs$cst$1524$error.cljs$core$IFn$_invoke$arity$1(c)],null)),b=$APP.cljs.core.conj.cljs$core$IFn$_invoke$arity$2(b,c);else{try{var h=$APP.sci.core.eval_form($APP.bb_web_ds_tools.workers.sci.sci_ctx,
c)}catch(l){h=new $APP.cljs.core.PersistentArrayMap(null,1,[$APP.cljs$cst$1524$error,["Eval Error: ",$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(l)].join("")],null)}var k=$APP.cljs.core.truth_($APP.cljs$cst$1524$error.cljs$core$IFn$_invoke$arity$1(h))?h:$APP.bb_web_ds_tools.workers.sci.prepare_for_transport(h);$APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,$APP.cljs$cst$1822$result,$APP.cljs$cst$1677$value,k],null));b=$APP.cljs.core.conj.cljs$core$IFn$_invoke$arity$2(b,
k)}}}catch(l){return $APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,$APP.cljs$cst$1524$error,$APP.cljs$cst$2509$text,$APP.cljs.core.str.cljs$core$IFn$_invoke$arity$1(l)],null))}}else return $APP.bb_web_ds_tools.workers.sci.post_msg(new $APP.cljs.core.PersistentArrayMap(null,2,[$APP.cljs$cst$139$type,cljs$cst$4534$warning,$APP.cljs$cst$2509$text,"Code is empty"],null))};
$APP.bb_web_ds_tools.workers.sci.init=function(){return self.addEventListener("message",function(a){var b=$APP.cognitect.transit.reader.cljs$core$IFn$_invoke$arity$1($APP.cljs$cst$2467$json);a=$APP.cognitect.transit.read(b,a.data);var c=$APP.cljs.core.__destructure_map(a);a=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$139$type);b=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$1757$code);c=$APP.cljs.core.get.cljs$core$IFn$_invoke$arity$2(c,$APP.cljs$cst$1755$datasets);
switch(a){case "eval":return $APP.bb_web_ds_tools.workers.sci.eval_code(b);case "update-datasets":b=$APP.bb_web_ds_tools.workers.sci._STAR_suppress_sync_STAR_;$APP.bb_web_ds_tools.workers.sci._STAR_suppress_sync_STAR_=!0;try{return $APP.cljs.core.reset_BANG_($APP.bb_web_ds_tools.workers.sci.datasets_atom,cljs_bean.core.__GT_clj.cljs$core$IFn$_invoke$arity$1(c))}finally{$APP.bb_web_ds_tools.workers.sci._STAR_suppress_sync_STAR_=b}default:return console.warn("Unknown message type:",a)}})};$APP.bb_web_ds_tools.workers.sci.init();
}).call(this);