importScripts("shared.js");
(function(){
'use strict';var $eb=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},afb=function(a,b,c){return arguments.length<=2?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)},bfb=function(a,b,c,d){return Array.prototype.splice.apply(a,afb(arguments,1))},cfb=function(a){switch(a){case '"':case ";":case "@":case "^":case "`":case "~":case "(":case ")":case "[":case "]":case "{":case "}":case "\\":return!0;
default:return!1}},I$=function(a){return $APP.fl(a)?new $APP.K(null,2,5,$APP.M,[a.yd(null),a.xd(null)],null):null},J$=function(a){return $APP.fl(a)?new $APP.K(null,2,5,$APP.M,[a.yd(null),a.xd(null)-1|0],null):null},dfb=function(a){a=$APP.w(a);for(var b=$APP.uc($APP.mg);;)if(a){var c=$APP.y(a);a=$APP.z(a);b=$APP.lg.g($APP.lg.g(b,$APP.Ob(c)),$APP.Pb(c))}else return $APP.w($APP.wc(b))},efb=function(a){throw $APP.ul.g("resolve-symbol is not implemented",new $APP.n(null,1,[$APP.nA,a],null));},ffb=function(a,
b,c){a===K$&&(a=c<0,$APP.Ll(b,a?c:a))},gfb=function(a){for(var b=new $APP.Va,c=a.Z(null);;){if('"'===c)return $APP.mi($APP.q.h(b));if(c==null)return $APP.Cl(a,$APP.Tn,$APP.D([b]));b.append(c);"\\"===c&&(c=a.Z(null),c==null&&$APP.Cl(a,$APP.Tn,$APP.D([b])),b.append(c));c=a.Z(null)}},L$=function(a,b,c){if(c==null)return $APP.lda(a,b);$APP.hJ.clear();for(b=c;;){if($APP.Jk(b)||cfb(b)||b==null)return b!=null&&a.Pc(null,b),$APP.hJ.toString();$APP.hJ.append(b);b=a.Z(null)}},hfb=function(a,b,c){b=1+b;$APP.Ed(a)!==
b&&$APP.jda(a);for(var d=1,e=0;;){if(d===b)return String.fromCharCode(e);var f=$APP.Tk($APP.C.g(a,d),c);if(f===-1)return $APP.oda($APP.C.g(a,d),a);e=f+e*c;d+=1}},ifb=function(a){var b=a.Z(null);if(b!=null){b=cfb(b)||$APP.Jk(b)?$APP.q.h(b):L$(a,$APP.Gda,b);var c=b.length;if(1===c)return b.charAt(0);if($APP.B.g(b,"newline"))return"\n";if($APP.B.g(b,"space"))return" ";if($APP.B.g(b,"tab"))return"\t";if($APP.B.g(b,"backspace"))return"\b";if($APP.B.g(b,"formfeed"))return"\f";if($APP.B.g(b,"return"))return"\r";
if($APP.p($APP.va(b,"u")))return b=hfb(b,4,16),c=b.charCodeAt(0),c>55295&&c<57344?$APP.qda(a,c.toString(16)):b;if($APP.p($APP.va(b,"o"))){--c;if(c>3)return $APP.rda(a,b);c=hfb(b,c,8);b=$APP.ii.g(b,1);return parseInt(b,8)<=255?c:$APP.Gl(a)}return $APP.wl(a,$APP.D(["Unsupported character: ",b,"."]))}return $APP.Hl(a)},jfb=function(a,b){return $APP.wl(a,$APP.D(["Unmatched delimiter ",b,"."]))},kfb=function(a,b){var c=J$(a),d=$APP.C.i(c,0,null);c=$APP.C.i(c,1,null);b=L$(a,$APP.im,b);if(b==null)return null;
switch(b){case "nil":return null;case "true":return!0;case "false":return!1;case "/":return $APP.jm;default:var e=$APP.Ql(b);if(e!=null){b=$APP.yi.g(e.V(null,0),e.V(null,1));e=b.K;if(d==null)d=null;else{var f=$APP.Zk(a);f=f==null?null:new $APP.n(null,1,[$APP.rl,f],null);var g=I$(a);a=$APP.C.i(g,0,null);g=$APP.C.i(g,1,null);d=$APP.sj.j($APP.D([f,new $APP.n(null,4,[$APP.sl,d,$APP.vm,c,$APP.XI,a,$APP.Xv,g],null)]))}d=e.call(b,null,d)}else d=$APP.Bl(a,$APP.im,b);return d}},lfb=function(a){var b=a.Z(null);
if($APP.Jk(b))return $APP.tda(a);b=L$(a,$APP.km,b);var c=$APP.Ql(b);if(c!=null){var d=c.V(null,0);c=c.V(null,1);if(":"===b.charAt(0)){if(d!=null)return d=$APP.yi.h($APP.ii.g(d,1)),d=$APP.E.g(null,d),$APP.p(d)?$APP.ti.g($APP.q.h(d),c):$APP.Bl(a,$APP.km,[":",$APP.q.h(b)].join(""));d=null;return $APP.p(d)?$APP.ti.g($APP.q.h(d),$APP.ii.g(c,1)):$APP.wl(a,$APP.D(["Invalid token: :",b]))}return $APP.ti.g(d,c)}return $APP.Bl(a,$APP.km,[":",$APP.q.h(b)].join(""))},mfb=function(a){if($APP.mb(M$))throw $APP.ul.g("Gensym literal not in syntax-quote",
new $APP.n(null,1,[$APP.uj,$APP.Bw],null));var b=$APP.E.g(M$,a);if($APP.p(b))return b;b=$APP.yi.h([$APP.ii.i($APP.Vh(a),0,$APP.Vh(a).length-1),"__",$APP.q.h($APP.Oi.g($APP.Upa,$APP.td)),"__auto__"].join(""));M$=$APP.Mh.i(M$,a,b);return b},nfb=function(a,b){return function(){var c=a!=null?a.B&262144||$APP.$c===a.he?!0:!1:!1;return c?$APP.w($APP.Ek.j($APP.Sd(a),$APP.sl,$APP.D([$APP.vm,$APP.XI,$APP.Xv,$APP.rl,$APP.jl]))):c}()?new $APP.G(null,$APP.xea,new $APP.G(null,b,new $APP.G(null,function(){var c=
$APP.Sd(a);return N$.h?N$.h(c):N$.call(null,c)}(),null,1,null),2,null),3,null):b},O$=function(a,b){a:{b=$APP.w(b);for(var c=$APP.uc($APP.mg);;)if(b){var d=$APP.y(b);c=$APP.lg.g(c,$APP.ie(d)&&$APP.B.g($APP.y(d),$APP.Vm)?new $APP.G(null,$APP.Wm,new $APP.G(null,$APP.Jd(d),null,1,null),2,null):$APP.ie(d)&&$APP.B.g($APP.y(d),$APP.Xm)?$APP.Jd(d):new $APP.G(null,$APP.Wm,new $APP.G(null,N$.h?N$.h(d):N$.call(null,d),null,1,null),2,null));b=$APP.z(b)}else{b=$APP.w($APP.wc(c));break a}b=void 0}b=new $APP.G(null,
$APP.Vla,new $APP.G(null,$APP.Ze($APP.KG,b),null,1,null),2,null);return $APP.p(a)?new $APP.G(null,$APP.hq,new $APP.G(null,a,new $APP.G(null,b,null,1,null),2,null),3,null):b},N$=function(a){if($APP.Xj(a))var b=new $APP.G(null,$APP.Tj,new $APP.G(null,a,null,1,null),2,null);else if(a instanceof $APP.t)b=new $APP.G(null,$APP.Tj,new $APP.G(null,$APP.p(function(){var c=$APP.mb($APP.bf(a));return c?$APP.wa($APP.Vh(a),"#"):c}())?mfb(a):function(){var c=$APP.q.h(a);return $APP.p($APP.wa(c,"."))?(c=$APP.yi.h($APP.ii.i(c,
0,c.length-1)),$APP.yi.h([$APP.q.h(efb.call(null,c)),"."].join(""))):efb.call(null,a)}(),null,1,null),2,null);else if($APP.ie(a)&&$APP.B.g($APP.y(a),$APP.Vm))b=$APP.Jd(a);else{if($APP.ie(a)&&$APP.B.g($APP.y(a),$APP.Xm))throw $APP.ul.g("unquote-splice not in list",new $APP.n(null,1,[$APP.uj,$APP.Bw],null));if($APP.Wd(a))if(a!=null&&(a.B&67108864||$APP.$c===a.Uj))b=a;else if($APP.ae(a))b=O$($APP.Ed(a)>=16?$APP.DB:$APP.Yka,dfb(a));else if($APP.ce(a))b=new $APP.G(null,$APP.Ema,new $APP.G(null,O$(null,
a),null,1,null),2,null);else if($APP.Xd(a))b=O$($APP.Lja,a);else if($APP.ie(a)||$APP.Ue(a))b=function(){var c=$APP.w(a);return c?O$(null,c):$APP.yk($APP.bna)}();else throw $APP.ul.g("Unknown Collection type",new $APP.n(null,1,[$APP.uj,$APP.ila],null));else b=a instanceof $APP.H||typeof a==="number"||typeof a==="string"||a==null||a instanceof Boolean||a===!0||a===!1||a instanceof RegExp?a:new $APP.G(null,$APP.Tj,new $APP.G(null,a,null,1,null),2,null)}return nfb(a,b)},ofb=function(a){return $APP.yi.h([-1===
a?"rest":["p",$APP.q.h(a)].join(""),"__",$APP.q.h($APP.Oi.g($APP.Upa,$APP.td)),"#"].join(""))},pfb=function(a){if($APP.p(P$)){var b=P$.call(null,a);if($APP.p(b))return b;b=ofb(a);P$=$APP.Mh.i(P$,a,b);return b}throw $APP.ul.g("Arg literal not in #()",new $APP.n(null,1,[$APP.uj,$APP.Bw],null));},sfb=function(a,b,c,d){b=a.Z(null);if($APP.p(b)){var e=qfb.h?qfb.h(b):qfb.call(null,b);if($APP.p(e))return e.u?e.u(a,b,c,d):e.call(null,a,b,c,d);a.Pc(null,b);return rfb.u?rfb.u(a,b,c,d):rfb.call(null,a,b,c,d)}return $APP.nda(a)},
tfb=function(a,b,c,d,e){for(var f=1,g=$APP.Tk(b,c);;){if(g===-1)return $APP.Fl(a,b);if(f!==d){var h=a.$b(null);var l=$APP.Jk(h);l||(l=Q$.h?Q$.h(h):Q$.call(null,h),l=$APP.p(l)?l:h==null);if($APP.p(l))return $APP.p(e)?$APP.pda(a,f,d):String.fromCharCode(g);l=$APP.Tk(h,c);a.Z(null);if(l===-1)return $APP.Fl(a,h);g=l+g*c;f+=1}else return String.fromCharCode(g)}},V$=function(a,b,c,d,e){var f=R$;R$=!0;try{a:{for(var g=J$(c),h=$APP.C.i(g,0,null),l=$APP.C.i(g,1,null),k=$APP.Hk(b),u=$APP.uc($APP.mg);;){var v=
S$?S$(c,!1,K$,k,d,e):T$.call(null,c,!1,K$,k,d,e);if(v===U$){var x=$APP.wc(u);break a}if(v===K$){x=$APP.ida(c,a,h,l,$APP.Ed(u));break a}u=$APP.lg.g(u,v)}x=void 0}return x}finally{R$=f}},ufb=function(a,b,c,d){var e=J$(a);b=$APP.C.i(e,0,null);e=$APP.C.i(e,1,null);var f=V$($APP.bm,")",a,c,d);d=I$(a);c=$APP.C.i(d,0,null);d=$APP.C.i(d,1,null);f=$APP.Vd(f)?$APP.kd:$APP.Vf.g($APP.yk,f);if($APP.p(b)){var g=$APP.sj.j;a=$APP.Zk(a);a=g.call($APP.sj,$APP.D([$APP.p(a)?new $APP.n(null,1,[$APP.rl,a],null):null,new $APP.n(null,
4,[$APP.sl,b,$APP.vm,e,$APP.XI,c,$APP.Xv,d],null)]))}else a=null;return $APP.Rd(f,a)},vfb=function(a,b,c,d){var e=J$(a);b=$APP.C.i(e,0,null);e=$APP.C.i(e,1,null);c=V$($APP.cm,"]",a,c,d);var f=I$(a);d=$APP.C.i(f,0,null);f=$APP.C.i(f,1,null);if($APP.p(b)){var g=$APP.sj.j;a=$APP.Zk(a);a=g.call($APP.sj,$APP.D([$APP.p(a)?new $APP.n(null,1,[$APP.rl,a],null):null,new $APP.n(null,4,[$APP.sl,b,$APP.vm,e,$APP.XI,d,$APP.Xv,f],null)]))}else a=null;return $APP.Rd(c,a)},wfb=function(a,b,c,d){var e=J$(a);b=$APP.C.i(e,
0,null);e=$APP.C.i(e,1,null);var f=V$($APP.dm,"}",a,c,d),g=$APP.Ed(f),h=$APP.em.g(2,f),l=$APP.Th(h);d=I$(a);c=$APP.C.i(d,0,null);d=$APP.C.i(d,1,null);!$APP.Tf(g)&&$APP.Al(a,b,e,f);$APP.B.g($APP.Ed(l),$APP.Ed(h))||$APP.Kl(a,$APP.dm,h);f=g<=2*$APP.fm?$APP.Wba($APP.uf(f)):$APP.eca($APP.uf(f));$APP.p(b)?(g=$APP.sj.j,a=$APP.Zk(a),a=g.call($APP.sj,$APP.D([$APP.p(a)?new $APP.n(null,1,[$APP.rl,a],null):null,new $APP.n(null,4,[$APP.sl,b,$APP.vm,e,$APP.XI,c,$APP.Xv,d],null)]))):a=null;return $APP.Rd(f,a)},
xfb=function(a,b){for(var c=function(){var g=new $APP.Va;g.append(b);return g}(),d=a.Z(null);;){if($APP.p(function(){var g=$APP.Jk(d);if(g)return g;g=Q$.h?Q$.h(d):Q$.call(null,d);return $APP.p(g)?g:d==null}())){var e=$APP.q.h(c);a.Pc(null,d);var f=$APP.Pl(e);return $APP.p(f)?f:$APP.wl(a,$APP.D(["Invalid number: ",e,"."]))}e=function(){var g=c;g.append(d);return g}();f=a.Z(null);c=e;d=f}},yfb=function(a){var b=a.Z(null);switch(b){case "t":return"\t";case "r":return"\r";case "n":return"\n";case "\\":return"\\";
case '"':return'"';case "b":return"\b";case "f":return"\f";case "u":return b=a.Z(null),-1===parseInt(b|0,16)?$APP.kda(a,b):tfb(a,b,16,4,!0);default:return $APP.Kk(b)?(b=tfb(a,b,8,3,!1),(b|0)>255?$APP.Gl(a):b):$APP.sda(a,b)}},zfb=function(a){for(var b=new $APP.Va,c=a.Z(null);;){if(c==null)return $APP.Cl(a,$APP.hm,$APP.D(['"',b]));switch(c){case "\\":var d=function(){var f=b;f.append(yfb(a));return f}(),e=a.Z(null);b=d;c=e;continue;case '"':return $APP.q.h(b);default:d=function(){var f=b;f.append(c);
return f}();e=a.Z(null);b=d;c=e;continue}break}},X$=function(a){return function(b,c,d,e){return new $APP.G(null,a,new $APP.G(null,W$?W$(b,!0,null,d,e):T$.call(null,b,!0,null,d,e),null,1,null),2,null)}},Afb=function(a,b,c,d){if(a instanceof $APP.el&&!$APP.Jk($APP.Vk(a)))return $APP.kl(a,function(){var h=J$(a),l=$APP.C.i(h,0,null),k=$APP.C.i(h,1,null),u=$APP.Nk(W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d));$APP.ae(u)||$APP.Il(a,u);h=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);return h!=null&&
(h.B&131072||$APP.$c===h.Nc)?(l=$APP.p($APP.p(l)?$APP.ie(h):l)?$APP.Mh.j(u,$APP.sl,l,$APP.D([$APP.vm,k])):u,h!=null&&(h.B&262144||$APP.$c===h.he)?$APP.Rd(h,$APP.sj.j($APP.D([$APP.Sd(h),l]))):h.H=l):$APP.Jl(a,h)});var e=J$(a);b=$APP.C.i(e,0,null);var f=$APP.C.i(e,1,null),g=$APP.Nk(W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d));$APP.ae(g)||$APP.Il(a,g);e=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);return e!=null&&(e.B&131072||$APP.$c===e.Nc)?(b=$APP.p($APP.p(b)?$APP.ie(e):b)?$APP.Mh.j(g,$APP.sl,
b,$APP.D([$APP.vm,f])):g,e!=null&&(e.B&262144||$APP.$c===e.he)?$APP.Rd(e,$APP.sj.j($APP.D([$APP.Sd(e),b]))):e.H=b):$APP.Jl(a,e)},Bfb=function(a,b,c,d){var e=J$(a);b=$APP.C.i(e,0,null);e=$APP.C.i(e,1,null);e=$APP.p(e)?e-1|0:null;var f=V$($APP.lm,"}",a,c,d);c=$APP.Th(f);var g=I$(a);d=$APP.C.i(g,0,null);g=$APP.C.i(g,1,null);$APP.B.g($APP.Ed(f),$APP.Ed(c))||$APP.wl(a,$APP.D([$APP.Kl(a,$APP.lm,f)]));$APP.p(b)?(f=$APP.sj.j,a=$APP.Zk(a),a=f.call($APP.sj,$APP.D([$APP.p(a)?new $APP.n(null,1,[$APP.rl,a],null):
null,new $APP.n(null,4,[$APP.sl,b,$APP.vm,e,$APP.XI,d,$APP.Xv,g],null)]))):a=null;return $APP.Rd(c,a)},Cfb=function(a,b,c,d){W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);return a},Dfb=function(a,b,c,d){b=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);return $APP.B.g($APP.Tda,b)?Number.NaN:$APP.B.g($APP.Uda,b)?Number.NEGATIVE_INFINITY:$APP.B.g($APP.Vda,b)?Number.POSITIVE_INFINITY:$APP.wl(a,$APP.D([["Invalid token: ##",$APP.q.h(b)].join("")]))},Efb=function(a,b,c,d){var e=Y$;Y$=!0;try{var f=S$?
S$(b,!1,K$,")",c,d):T$.call(null,b,!1,K$,")",c,d);ffb(f,b,a);return f===U$?U$:null}finally{Y$=e}},Gfb=function(a,b,c,d){var e=$APP.fl(a)?$APP.Xk(a):-1;a:{for(var f=Ffb,g=null;;)if(f===Ffb){f=e;g=a;var h=c,l=d,k=S$?S$(g,!1,K$,")",h,l):T$.call(null,g,!1,K$,")",h,l);ffb(k,g,f);if($APP.B.g(k,U$))f=U$;else{var u=g,v=k;$APP.p($APP.E.g($APP.$pa,v))&&$APP.wl(u,$APP.D(["Feature name ",v," is reserved"]));u=g;v=h;(k instanceof $APP.H?$APP.B.g($APP.tm,k)||$APP.ve($APP.E.g(v,$APP.In),k):$APP.wl(u,$APP.D(["Feature should be a keyword: ",
k])))?(h=S$?S$(g,!1,K$,")",h,l):T$.call(null,g,!1,K$,")",h,l),ffb(h,g,f),h===U$&&(f<0?$APP.wl(g,$APP.D(["read-cond requires an even number of forms"])):$APP.wl(g,$APP.D(["read-cond starting on line ",f," requires an even number of forms"]))),f=h):(f=Efb(f,g,h,l),f=$APP.p(f)?f:Ffb)}if(f===U$){c=U$;break a}g=null}else if(g!==U$)g=Efb(e,a,c,d);else{c=f;break a}c=void 0}return c===U$?a:$APP.p(b)?c!=null&&(c.B&16777216||$APP.$c===c.Yg)?(b=$APP.uf(c),$eb(bfb,d,0,0).apply(null,b),a):$APP.wl(a,$APP.D(["Spliced form list in read-cond-splicing must implement ISequential"])):
c},Hfb=function(a,b,c,d){if($APP.mb(function(){if($APP.p(c)){var g=$APP.Kn.h(c),h=new $APP.Ph(null,new $APP.n(null,2,[$APP.Ln,null,$APP.Eq,null],null),null);return h.h?h.h(g):h.call(null,g)}return c}()))throw $APP.ul.g("Conditional read not allowed",new $APP.n(null,1,[$APP.uj,$APP.Lia],null));var e=a.Z(null);if($APP.p(e))if(e=(b=$APP.B.g(e,"@"))?a.Z(null):e,b&&($APP.p(R$)||$APP.wl(a,$APP.D(["cond-splice not in list"]))),e=$APP.Jk(e)?$APP.Nl(a):e,$APP.p(e)){if($APP.Lh.g(e,"("))throw $APP.ul.g("read-cond body must be a list",
new $APP.n(null,1,[$APP.uj,$APP.Lia],null));var f=Y$;Y$=function(){var g=Y$;return $APP.p(g)?g:$APP.B.g($APP.Ln,$APP.Kn.h(c))}();try{return $APP.p(Y$)?$APP.ada(ufb(a,e,c,d),b):Gfb(a,b,c,d)}finally{Y$=f}}else return $APP.Hl(a);else return $APP.Hl(a)},Ifb=function(a,b,c,d){if($APP.p(P$))throw $APP.ul.g("Nested #()s are not allowed",new $APP.n(null,1,[$APP.uj,$APP.Bw],null));b=P$;P$=$APP.Ku();try{$APP.Wk(a,"(");var e=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);var f=$APP.ic(P$);if(f){var g=$APP.Ag($APP.y(f));
a:{a=1;for(var h=$APP.uc($APP.mg);;){if(a>g){var l=$APP.wc(h);break a}c=a+1;d=$APP.lg;var k=d.g;f=h;var u=$APP.E.g(P$,a);var v=$APP.p(u)?u:ofb(a);var x=k.call(d,f,v);a=c;h=x}l=void 0}var A=$APP.p(P$.call(null,-1))?$APP.We.j(l,$APP.zj,$APP.D([P$.call(null,-1)])):l}else A=$APP.mg;return new $APP.G(null,$APP.Oj,new $APP.G(null,A,new $APP.G(null,e,null,1,null),2,null),3,null)}finally{P$=b}},Jfb=function(a,b,c,d){if(P$==null)return kfb(a,b);b=a.$b(null);if($APP.Jk(b)||cfb(b)||b==null)return pfb(1);if($APP.B.g(b,
"\x26"))return a.Z(null),pfb(-1);a=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);if($APP.me(a))return pfb(a);throw $APP.ul.g("Arg literal must be %, %\x26 or %integer",new $APP.n(null,1,[$APP.uj,$APP.Bw],null));},Kfb=function(a,b,c,d){b=a.$b(null);$APP.p(b)?$APP.B.g("@",b)?(b=X$($APP.Xm),a.Z(null),a=b(a,"@",c,d)):a=X$($APP.Vm)(a,"~",c,d):a=null;return a},Lfb=function(a,b,c,d){b=M$;M$=$APP.Bf;try{return N$(W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d))}finally{M$=b}},Mfb=function(a,b,c,d){var e=
J$(a);b=$APP.C.i(e,0,null);e=$APP.C.i(e,1,null);var f=L$(a,$APP.mm,$APP.Uk(a)),g=$APP.B.g(f,":")?null.name:$APP.B.g(":",$APP.y(f))?function(){var l=f==null?null:$APP.ii.g(f,1);l=l==null?null:$APP.Ql(l);l=l==null?null:$APP.Sk(l);l=l==null?null:$APP.yi.h(l);if(l==null)l=null;else{var k=$APP.E.g(null,l);$APP.p(k)?l=k:($APP.ov==null&&($APP.ov=$APP.Ni.h($APP.Bf)),k=$APP.E.g($APP.r($APP.ov),l),k!=null?l=k:(k=$APP.hk(l),k==null?l=null:(k=new $APP.fk(k,l),$APP.Oi.u($APP.ov,$APP.Mh,l,k),l=k)),l=$APP.p(l)?
$APP.yi.h(l.name):null)}return l}():function(){var l=f==null?null:$APP.Ql(f);return l==null?null:$APP.Sk(l)}();if($APP.p(g)){if($APP.Nl(a)==="{"){d=V$($APP.mm,"}",a,c,d);var h=I$(a);c=$APP.C.i(h,0,null);h=$APP.C.i(h,1,null);$APP.Uf($APP.Ed(d))&&$APP.Al(a,null,null,d);g=$APP.Rk($APP.q.h(g),$APP.em.g(2,d));d=$APP.em.g(2,$APP.ld(d));$APP.B.g($APP.Ed($APP.Th(g)),$APP.Ed(g))||$APP.Kl(a,$APP.mm,g);return $APP.Rd($APP.Wh(g,d),$APP.p(b)?$APP.sj.j($APP.D([function(){var l=$APP.Zk(a);return $APP.p(l)?new $APP.n(null,
1,[$APP.rl,l],null):null}(),new $APP.n(null,4,[$APP.sl,b,$APP.vm,e,$APP.XI,c,$APP.Xv,h],null)])):null)}return $APP.uda(a,f)}return $APP.vda(a,f)},Q$=function(a){switch(a){case '"':return zfb;case ":":return lfb;case ";":return $APP.om;case "'":return X$($APP.Tj);case "@":return X$($APP.eo);case "^":return Afb;case "`":return Lfb;case "~":return Kfb;case "(":return ufb;case ")":return jfb;case "[":return vfb;case "]":return jfb;case "{":return wfb;case "}":return jfb;case "\\":return ifb;case "%":return Jfb;
case "#":return sfb;default:return null}},qfb=function(a){switch(a){case "^":return Afb;case "'":return X$($APP.Sj);case "(":return Ifb;case "{":return Bfb;case "\x3c":return $APP.Rl("Unreadable form");case "\x3d":return $APP.Rl("read-eval not supported");case '"':return gfb;case "!":return $APP.om;case "_":return Cfb;case "?":return Hfb;case ":":return Mfb;case "#":return Dfb;default:return null}},rfb=function(a,b,c,d){b=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d);b instanceof $APP.t||$APP.wda(a,
b);if($APP.p(Y$))return $APP.Zj(b,W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d));var e=$APP.aqa.call(null,b);e=$APP.p(e)?e:$APP.qm.h?$APP.qm.h(b):$APP.qm.call(null,b);return $APP.p(e)?(a=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d),e.h?e.h(a):e.call(null,a)):$APP.p(null)?(e=null,a=W$?W$(a,!0,null,c,d):T$.call(null,a,!0,null,c,d),e.g?e.g(b,a):e.call(null,b,a)):$APP.xda(a,b)},Nfb=function(a,b,c,d,e,f){for(;;){if(a instanceof $APP.el&&!$APP.Jk(a.$b(null)))return $APP.kl(a,function(){for(;;){if(f.length==
0){var l=a.Z(null);if($APP.Jk(l))continue;else{if(l==null)return b?$APP.Ll(a,null):c;if(l===d)return U$;if($APP.Ml(a,l))return xfb(a,l);var k=Q$(l);if(k!=null)if(l=k.u?k.u(a,l,e,f):k.call(null,a,l,e,f),l===a)continue;else return l;else return kfb(a,l)}}else return l=f[0],$APP.Ea(f,0),l;break}});if(f.length==0){var g=a.Z(null);if($APP.Jk(g))continue;else{if(g==null)return b?$APP.Ll(a,null):c;if(g===d)return U$;if($APP.Ml(a,g))return xfb(a,g);var h=Q$(g);if(h!=null)if(g=h.u?h.u(a,g,e,f):h.call(null,
a,g,e,f),g===a)continue;else return g;else return kfb(a,g)}}else return g=f[0],$APP.Ea(f,0),g;break}},T$=function(a){switch(arguments.length){case 5:return W$(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return S$(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:throw Error(["Invalid arity: ",$APP.q.h(arguments.length)].join(""));}},W$=function(a,b,c,d,e){return S$(a,b,c,null,d,e)},S$=function(a,b,c,d,e,f){try{return Nfb(a,b,c,d,e,
f)}catch(g){if(g instanceof Error){b=g;if(b instanceof $APP.oj){c=$APP.pj(b);if($APP.B.g($APP.ql,$APP.uj.h(c)))throw b;throw $APP.ul.i(b.message,$APP.sj.j($APP.D([new $APP.n(null,1,[$APP.uj,$APP.ql],null),c,$APP.fl(a)?new $APP.n(null,3,[$APP.sl,a.yd(null),$APP.vm,a.xd(null),$APP.rl,a.Df],null):null])),b);}throw $APP.ul.i(b.message,$APP.sj.j($APP.D([new $APP.n(null,1,[$APP.uj,$APP.ql],null),$APP.fl(a)?new $APP.n(null,3,[$APP.sl,a.yd(null),$APP.vm,a.xd(null),$APP.rl,a.Df],null):null])),b);}throw g;
}},Z$=function(a){return postMessage($APP.zt(a))},K$={},U$={},R$=!1,Y$=!1,Ffb={},P$=null,M$=null,Ofb=new $APP.t(null,"datasets","datasets",-758071350,null);var Pfb=$APP.Ni.h($APP.Bf),Qfb=$APP.at(new $APP.n(null,1,[$APP.yp,new $APP.n(null,3,[$APP.Vp,new $APP.n(null,1,[$APP.PH,function(){function a(c){var d=null;if(arguments.length>0){d=0;for(var e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new $APP.hd(e,0,null)}return b.call(this,d)}function b(c){return Z$(new $APP.n(null,2,[$APP.uj,$APP.ZF,$APP.mB,$APP.Vf.g($APP.q,$APP.nl.g(" ",c))],null))}a.o=0;a.v=function(c){c=$APP.w(c);return b(c)};a.j=b;return a}()],null),$APP.Ela,new $APP.n(null,
2,[$APP.Uma,function(a){return Z$(new $APP.n(null,2,[$APP.uj,$APP.qo,$APP.FG,a],null))},$APP.rka,function(){Z$(new $APP.n(null,2,[$APP.uj,$APP.VC,$APP.mB,"rf/subscribe is not supported in the worker."],null));return $APP.Ni.h(null)}],null),$APP.Xs,new $APP.n(null,1,[Ofb,Pfb],null)],null)],null));$APP.Vha(Qfb,"(require '[clojure.string :as str] '[clojure.set :as set] '[clojure.edn :as edn])");self.addEventListener("message",function(a){a=$APP.vt(a.data,$APP.D([$APP.wt,!0]));var b=$APP.Cf(a);a=$APP.E.g(b,$APP.uj);var c=$APP.E.g(b,$APP.Ex);b=$APP.E.g(b,$APP.ty);switch(a){case "eval":a:{a=$APP.gl(c);try{for(c=$APP.mg;;){try{var d=S$(a,!1,$APP.yl,null,$APP.Bf,$APP.uf($APP.mg))}catch(A){d=new $APP.n(null,1,[$APP.zG,["Read Error: ",$APP.q.h(A)].join("")],null)}if($APP.B.g(d,$APP.yl)){var e=c;break a}var f=$APP.ae(d);var g=f?$APP.zG.h(d):f;if($APP.p(g))Z$(new $APP.n(null,2,[$APP.uj,$APP.zG,$APP.mB,
$APP.zG.h(d)],null)),c=$APP.We.g(c,d);else{try{b=void 0;var h=d,l=Qfb,k=$APP.Mh.i,u=$APP.vp.h(l);b=$APP.p(u)?u:$APP.$m.s();var v=k.call($APP.Mh,l,$APP.vp,b);var x=$APP.uL(v,h)}catch(A){x=new $APP.n(null,1,[$APP.zG,["Eval Error: ",$APP.q.h(A)].join("")],null)}Z$(new $APP.n(null,2,[$APP.uj,$APP.nH,$APP.GG,x],null));c=$APP.We.g(c,x)}}}catch(A){e=Z$(new $APP.n(null,2,[$APP.uj,$APP.zG,$APP.mB,$APP.q.h(A)],null));break a}e=void 0}return e;case "update-datasets":return $APP.Zf(Pfb,b);default:return console.warn("Unknown message type:",
a)}});
}).call(this);