name: Deploy to GitHub Pages

on:
  push:
    branches:
      - releases

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        ref: releases

    - name: Link node_modules
      run: ln -s /opt/app/node_modules .

    - name: Build app
      run: npm run build

    - name: Run Postinstall
      run: npm run postinstall

    - name: Compile test-interactive
      run: npx shadow-cljs compile test-interactive

    - name: Compile storybook
      run: npx shadow-cljs compile stories

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
