name: Functional Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Link node_modules
      run: ln -s /opt/app/node_modules .

    - name: Cache .shadow-cljs and node modules
      uses: actions/cache@v3
      with:
        path: |
          .shadow-cljs
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          .cpcache
          node_modules
        key: ${{ runner.os }}-shadow-cljs-${{ hashFiles('deps.edn', 'package.json')}}
        restore-keys: |
          ${{ runner.os }}-shadow-cljs-

    - name: Run functional tests
      run: npm test
